/***** 관리자 관리 테이블 변경 ******/

ALTER TABLE T_MANAGER RENAME COLUMN SITE_CODE TO SITE_CODE_META;


/***** 메뉴 관리 테이블 재 구성 ******/

ALTER TABLE T_MENU RENAME to T_MENU_;

CREATE TABLE T_MENU (
  MENU_IDX NUMBER (22) DEFAULT 0 NOT NULL
, MENU_PCODE VARCHAR2 (50) DEFAULT NULL
, MENU_CODE VARCHAR2 (50) NOT NULL
, MENU_NAME VARCHAR2 (150) DEFAULT NULL
, MENU_TYPE CHAR (1) DEFAULT '5'
, MENU_SUBTYPE VARCHAR2 (300) DEFAULT NULL
, MENU_CATEGORY VARCHAR2 (300) DEFAULT NULL
, MENU_URL VARCHAR2 (300) DEFAULT NULL
, MENU_MNGURL VARCHAR2 (300) DEFAULT NULL
, MENU_SITECODE VARCHAR2 (60) DEFAULT NULL
, MENU_DEPTH NUMBER (22) DEFAULT NULL
, MENU_ORDER NUMBER (22) DEFAULT NULL
, MENU_FULLORDER VARCHAR2 (30) DEFAULT NULL
, MENU_PFULLCODE VARCHAR2 (1000) DEFAULT NULL
, MENU_PFULLNAME VARCHAR2 (1000) DEFAULT NULL
, MENU_NAVI VARCHAR2 (1000) DEFAULT NULL
, MENU_MEMO VARCHAR2 (1000) DEFAULT NULL
, MENU_CONTENTS NUMBER (22) DEFAULT NULL
, MENU_MAINPAGE NUMBER (22) DEFAULT 0
, MENU_SHOWTYPE CHAR (1) DEFAULT '0'
, MENU_USETYPE CHAR (1) DEFAULT '0'
, MENU_USEFIXWIDTH CHAR (1) DEFAULT '0'
, MENU_CHARGEUSEYN CHAR (1) DEFAULT 'N'
, MENU_RESEARCHUSEYN CHAR (1) DEFAULT 'N'
, MENU_LNBUSEYN CHAR (1) DEFAULT 'Y'
, MENU_QRUSEYN CHAR (1) DEFAULT 'N'
, MENU_SNSSHAREYN CHAR (1) DEFAULT 'N'
, MENU_USEYN CHAR (1) DEFAULT 'Y'
, MNG_ID VARCHAR2 (60) DEFAULT NULL
, REGDT DATE DEFAULT SYSDATE
, UPDDT DATE DEFAULT SYSDATE
, DELDT DATE DEFAULT NULL
, REGMEMID VARCHAR2 (60) DEFAULT NULL
, UPDMEMID VARCHAR2 (60) DEFAULT NULL
, DELMEMID VARCHAR2 (60) DEFAULT NULL
, DELYN CHAR (1) DEFAULT 'N'
);
COMMENT ON TABLE T_MENU IS '메뉴관리';
COMMENT ON COLUMN T_MENU.MENU_IDX IS '메뉴인덱스';
COMMENT ON COLUMN T_MENU.MENU_CODE IS '메뉴코드';
COMMENT ON COLUMN T_MENU.MENU_NAME IS '메뉴이름';
COMMENT ON COLUMN T_MENU.MENU_TYPE IS '메뉴타입';
COMMENT ON COLUMN T_MENU.MENU_SUBTYPE IS '메뉴하위타입';
COMMENT ON COLUMN T_MENU.MENU_CATEGORY IS '메뉴카테고리';
COMMENT ON COLUMN T_MENU.MENU_URL IS '링크주소';
COMMENT ON COLUMN T_MENU.MENU_NAVI IS '네비게이션';
COMMENT ON COLUMN T_MENU.MENU_DEPTH IS '뎁스';
COMMENT ON COLUMN T_MENU.MENU_PCODE IS '부모메뉴코드';
COMMENT ON COLUMN T_MENU.MENU_ORDER IS '순서';
COMMENT ON COLUMN T_MENU.MENU_MEMO IS '메모';
COMMENT ON COLUMN T_MENU.MENU_USEYN IS '사용여부';
COMMENT ON COLUMN T_MENU.MENU_SHOWTYPE IS '메뉴방식';
COMMENT ON COLUMN T_MENU.MENU_MNGURL IS '관리자주소';
COMMENT ON COLUMN T_MENU.MENU_CHARGEUSEYN IS '담당자사용여부';
COMMENT ON COLUMN T_MENU.MNG_ID IS '담당자아이디';
COMMENT ON COLUMN T_MENU.MENU_LNBUSEYN IS '사이드메뉴사용여부';
COMMENT ON COLUMN T_MENU.MENU_RESEARCHUSEYN IS '만족도사용여부';
COMMENT ON COLUMN T_MENU.MENU_PFULLNAME IS '메뉴전체이름';
COMMENT ON COLUMN T_MENU.MENU_PFULLCODE IS '메뉴전체코드';
COMMENT ON COLUMN T_MENU.MENU_USETYPE IS '메뉴사용구분';
COMMENT ON COLUMN T_MENU.MENU_QRUSEYN IS 'QR사용여부';
COMMENT ON COLUMN T_MENU.REGDT IS '등록일';
COMMENT ON COLUMN T_MENU.UPDDT IS '수정일';
COMMENT ON COLUMN T_MENU.DELDT IS '삭제일';
COMMENT ON COLUMN T_MENU.REGMEMID IS '등록자아이디';
COMMENT ON COLUMN T_MENU.UPDMEMID IS '수정자아이디';
COMMENT ON COLUMN T_MENU.DELMEMID IS '삭제자아이디';
COMMENT ON COLUMN T_MENU.DELYN IS '삭제여부';
COMMENT ON COLUMN T_MENU.MENU_FULLORDER IS '계층유지순서';
COMMENT ON COLUMN T_MENU.MENU_MAINPAGE IS '메인페이지노출';
COMMENT ON COLUMN T_MENU.MENU_SNSSHAREYN IS 'SNS공유사용여부';
COMMENT ON COLUMN T_MENU.MENU_USEFIXWIDTH IS '페이지형태';
COMMENT ON COLUMN T_MENU.MENU_SITECODE IS '메뉴가속한사이트';
COMMENT ON COLUMN T_MENU.MENU_CONTENTS IS '메뉴컨텐츠인덱스';

ALTER TABLE T_MENU ADD CONSTRAINT T_MENU_PK PRIMARY KEY (MENU_IDX);
CREATE SEQUENCE t_menu_seq    START WITH 1    INCREMENT BY 1;

INSERT INTO T_MENU (
MENU_IDX
, MENU_PCODE
, MENU_CODE
, MENU_NAME
, MENU_TYPE
, MENU_SUBTYPE
, MENU_URL
, MENU_MNGURL
, MENU_SITECODE
, MENU_DEPTH
, MENU_ORDER
, MENU_FULLORDER
, MENU_PFULLCODE
, MENU_PFULLNAME
, MENU_NAVI
, MENU_MEMO
, MENU_MAINPAGE
, MENU_SHOWTYPE
, MENU_USETYPE
, MENU_USEFIXWIDTH
, MENU_CHARGEUSEYN
, MENU_RESEARCHUSEYN
, MENU_LNBUSEYN
, MENU_QRUSEYN
, MENU_SNSSHAREYN
, MENU_USEYN
, MNG_ID
, REGDT
, UPDDT
, DELDT
, REGMEMID
, UPDMEMID
, DELMEMID)

SELECT
t_menu_seq.nextval
, MENU_PCODE
, MENU_CODE
, MENU_NAME
, MENU_TYPE
, MENU_SUBTYPE
, MENU_URL
, MENU_MNGURL
, MENU_SITECODE
, MENU_DEPTH
, MENU_ORDER
, MENU_FULLORDER
, MENU_PFULLCODE
, MENU_PFULLNAME
, MENU_NAVI
, MENU_MEMO
, MENU_MAINPAGE
, MENU_SHOWTYPE
, MENU_USETYPE
, MENU_USEFIXWIDTH
, MENU_CHARGEUSEYN
, MENU_RESEARCHUSEYN
, MENU_LNBUSEYN
, MENU_QRUSEYN
, MENU_SNSSHAREYN
, MENU_USEYN
, MNG_ID
, REGDT
, UPDDT
, DELDT
, REGMEMID
, UPDMEMID
, DELMEMID FROM T_MENU_


/***** 게시판설정 관리 테이블 재 구성 ******/

ALTER TABLE T_BOARD_CONFIG RENAME to T_BOARD_CONFIG_;
CREATE TABLE T_BOARD_CONFIG
(
  BC_ID            VARCHAR2(150 BYTE)           DEFAULT ''                    NOT NULL,
  BC_NAME          VARCHAR2(300 BYTE)           DEFAULT NULL,
  BC_SKIN          VARCHAR2(60 BYTE)            DEFAULT NULL,
  BC_TYPE          CHAR(1 BYTE)                 DEFAULT '1',
  BC_TOPINFO       VARCHAR2(765 BYTE)           DEFAULT NULL,
  BC_VIEWCOUNT     NUMBER(6)                    DEFAULT NULL,
  BC_DEFAULTPAGE   VARCHAR2(150 BYTE)           DEFAULT NULL,
  BC_LIST          VARCHAR2(30 BYTE)            DEFAULT '100',
  BC_VIEW          VARCHAR2(30 BYTE)            DEFAULT '100',
  BC_REGIST        VARCHAR2(30 BYTE)            DEFAULT '900',
  BC_UPDATE        VARCHAR2(30 BYTE)            DEFAULT '900',
  BC_REPLY         VARCHAR2(30 BYTE)            DEFAULT '900',
  BC_MNGR_LIST     VARCHAR2(30 BYTE)            DEFAULT NULL,
  BC_MNGR_VIEW     VARCHAR2(30 BYTE)            DEFAULT NULL,
  BC_MNGR_REGIST   VARCHAR2(30 BYTE)            DEFAULT NULL,
  BC_MNGR_UPDATE   VARCHAR2(30 BYTE)            DEFAULT NULL,
  BC_MNGR_REPLY    VARCHAR2(30 BYTE)            DEFAULT NULL,
  BC_REPLYYN       CHAR(1 BYTE)                 DEFAULT NULL,
  BC_SECRETYN      CHAR(1 BYTE)                 DEFAULT NULL,
  BC_NOTICEYN      CHAR(1 BYTE)                 DEFAULT NULL,
  BC_EDITORYN      CHAR(1 BYTE)                 DEFAULT NULL,
  BC_PREVNEXTYN    CHAR(1 BYTE)                 DEFAULT NULL,
  BC_KOGLYN        CHAR(1 BYTE)                 DEFAULT NULL,
  BC_COMMENT       NUMBER(11)                   DEFAULT '0',
  BC_RSS           CHAR(1 BYTE)                 DEFAULT NULL,
  BC_GROUPYN       CHAR(1 BYTE)                 DEFAULT NULL,
  BC_GROUPCODE     VARCHAR2(60 BYTE)            DEFAULT NULL,
  BC_FILEYN        CHAR(1 BYTE)                 DEFAULT NULL,
  BC_FILECOUNT     NUMBER(6)                    DEFAULT NULL,
  BC_FILESIZE      NUMBER(6)                    DEFAULT NULL,
  BC_FILETYPEDESC  VARCHAR2(300 BYTE)           DEFAULT 'all',
  BC_THUMBYN       CHAR(1 BYTE)                 DEFAULT NULL,
  BC_THUMBCOUNT    NUMBER(6)                    DEFAULT '1',
  BC_THUMBWIDTH    NUMBER(6)                    DEFAULT NULL,
  BC_THUMBHEIGHT   NUMBER(6)                    DEFAULT NULL,
  BC_THUMBRATIOYN  CHAR(1 BYTE)                 DEFAULT NULL,
  BC_EXTCOLUMNINFO VARCHAR2(4000 BYTE)         	DEFAULT NULL,
  REGDT            DATE                 		DEFAULT SYSDATE               NOT NULL,
  UPDDT            DATE                 		DEFAULT SYSDATE               NOT NULL,
  DELDT            DATE                     	DEFAULT NULL,
  REGMEMID         VARCHAR2(60 BYTE)            DEFAULT NULL,
  UPDMEMID         VARCHAR2(60 BYTE)            DEFAULT NULL,
  DELMEMID         VARCHAR2(60 BYTE)            DEFAULT NULL,
  DELYN            CHAR(1 BYTE)                 DEFAULT NULL
);
COMMENT ON TABLE T_BOARD_CONFIG IS '게시판설정관리';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_ID IS '게시판아이디';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_NAME IS '게시판이름';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_SKIN IS '게시판스킨';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_TYPE IS '게시판유형(1공통.2커스텀)';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_TOPINFO IS '상단정보';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_VIEWCOUNT IS '게시물갯수';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_DEFAULTPAGE IS '기본페이지(리스트,뷰)';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_LIST IS '목록권한';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_VIEW IS '조회권한';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_REGIST IS '등록권한';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_UPDATE IS '수정권한';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_REPLY IS '답변권한';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_MNGR_LIST IS '관리자 목록권한';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_MNGR_VIEW IS '관리자 조회권한';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_MNGR_REGIST IS '관리자 등록권한';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_MNGR_UPDATE IS '관리자 수정권한';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_MNGR_REPLY IS '관리자 답변권한';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_REPLYYN IS '답글사용여부';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_SECRETYN IS '비밀글사용여부';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_NOTICEYN IS '공지글사용여부';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_EDITORYN IS '에디터사용여부';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_PREVNEXTYN IS '이전/다음사용여부';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_KOGLYN IS '공공누리사용여부';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_COMMENT IS '댓글 사용어부';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_RSS IS 'RSS 사용 여부';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_GROUPYN IS '카테고리사용여부';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_GROUPCODE IS '카테고리코드';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_FILEYN IS '첨부사용여부';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_FILECOUNT IS '첨부갯수';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_FILESIZE IS '첨부용량';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_FILETYPEDESC IS '첨부파일 확장자 descripter';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_THUMBYN IS '썸네일사용여부';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_THUMBCOUNT IS '썸네일갯수';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_THUMBWIDTH IS '썸네일 가로사이즈';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_THUMBHEIGHT IS '썸네일 세로사이즈';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_THUMBRATIOYN IS '비율유지 Y유지N고정';
COMMENT ON COLUMN T_BOARD_CONFIG.BC_EXTCOLUMNINFO IS '확장컬럼정보';
COMMENT ON COLUMN T_BOARD_CONFIG.REGDT IS '등록일';
COMMENT ON COLUMN T_BOARD_CONFIG.UPDDT IS '수정일';
COMMENT ON COLUMN T_BOARD_CONFIG.DELDT IS '삭제일';
COMMENT ON COLUMN T_BOARD_CONFIG.REGMEMID IS '등록자아이디';
COMMENT ON COLUMN T_BOARD_CONFIG.UPDMEMID IS '수정자아이디';
COMMENT ON COLUMN T_BOARD_CONFIG.DELMEMID IS '삭제자아이디';
COMMENT ON COLUMN T_BOARD_CONFIG.DELYN IS '삭제여부';
ALTER TABLE T_BOARD_CONFIG ADD CONSTRAINT T_BOARD_CONFIG_PK PRIMARY KEY (BC_ID);
CREATE SEQUENCE T_BOARD_CONFIG_SEQ START WITH 1 INCREMENT BY 1;


INSERT INTO T_BOARD_CONFIG (
  BC_ID,
  BC_NAME,
  BC_SKIN,
  BC_TYPE,
  BC_TOPINFO,
  BC_VIEWCOUNT,
  BC_DEFAULTPAGE,
  BC_LIST ,
  BC_VIEW ,
  BC_REGIST,
  BC_UPDATE        ,
  BC_REPLY         ,
  BC_MNGR_LIST    ,
  BC_MNGR_VIEW     ,
  BC_MNGR_REGIST  ,
  BC_MNGR_UPDATE  ,
  BC_MNGR_REPLY    ,
  BC_REPLYYN      ,
  BC_SECRETYN      ,
  BC_NOTICEYN     ,
  BC_EDITORYN      ,
  BC_PREVNEXTYN    ,
  BC_KOGLYN       ,
  BC_COMMENT       ,
  BC_RSS           ,
  BC_GROUPYN       ,
  BC_GROUPCODE     ,
  BC_FILEYN        ,
  BC_FILECOUNT     ,
  BC_FILESIZE      ,
  BC_FILETYPEDESC  ,
  BC_THUMBYN       ,
  BC_THUMBCOUNT    ,
  BC_THUMBWIDTH    ,
  BC_THUMBHEIGHT   ,
  BC_THUMBRATIOYN  ,
  REGDT            ,
  UPDDT            ,
  DELDT            ,
  REGMEMID         ,
  UPDMEMID         ,
  DELMEMID         ,
  DELYN
  )
SELECT
  BC_ID,
  BC_NAME,
  BC_SKIN,
  BC_TYPE,
  BC_TOPINFO,
  BC_VIEWCOUNT,
  BC_DEFAULTPAGE,
  BC_LIST ,
  BC_VIEW ,
  BC_REGIST,
  BC_UPDATE        ,
  BC_REPLY         ,
  BC_MNGR_LIST    ,
  BC_MNGR_VIEW     ,
  BC_MNGR_REGIST  ,
  BC_MNGR_UPDATE  ,
  BC_MNGR_REPLY    ,
  BC_REPLYYN      ,
  BC_SECRETYN      ,
  BC_NOTICEYN     ,
  BC_EDITORYN      ,
  BC_PREVNEXTYN    ,
  BC_KOGLYN       ,
  BC_COMMENT       ,
  BC_RSS           ,
  BC_GROUPYN       ,
  BC_GROUPCODE     ,
  BC_FILEYN        ,
  BC_FILECOUNT     ,
  BC_FILESIZE      ,
  BC_FILETYPEDESC  ,
  BC_THUMBYN       ,
  BC_THUMBCOUNT    ,
  BC_THUMBWIDTH    ,
  BC_THUMBHEIGHT   ,
  BC_THUMBRATIOYN  ,
  REGDT            ,
  UPDDT            ,
  DELDT            ,
  REGMEMID         ,
  UPDMEMID         ,
  DELMEMID         ,
  DELYN FROM T_BOARD_CONFIG_


/***** 통합게시판 테이블 재 구성 ******/
ALTER TABLE T_BOARD RENAME to T_BOARD_;
ALTER TABLE T_BOARD_ DROP PRIMARY KEY CASCADE;
DROP INDEX T_BOARD_BCID;

CREATE TABLE T_BOARD
(
  BD_IDX            NUMBER(20)                  DEFAULT '0'                   NOT NULL,
  BC_ID             VARCHAR2(60 BYTE)           DEFAULT NULL,
  BD_CODE           VARCHAR2(60 BYTE)           DEFAULT NULL,
  BD_WRITER         VARCHAR2(60 BYTE)           DEFAULT NULL,
  BD_TITLE          VARCHAR2(300 BYTE)          DEFAULT NULL,
  BD_CONTENT        CLOB						DEFAULT NULL,
  BD_CONTENT_TEXT   CLOB						DEFAULT NULL,
  BD_READNUM        NUMBER(11)                  DEFAULT 0,
  BD_PASSWD         VARCHAR2(300 BYTE)          DEFAULT NULL,
  BD_HTMLYN         CHAR(1 BYTE)                DEFAULT 'N',
  BD_NOTICE         CHAR(1 BYTE)                DEFAULT '0',
  BD_NOTICE_TERMYN  CHAR(1 BYTE)                DEFAULT 'N',
  BD_NOTICE_SDT     VARCHAR2(30 BYTE)           DEFAULT NULL,
  BD_NOTICE_EDT     VARCHAR2(30 BYTE)           DEFAULT NULL,
  BD_USEYN          CHAR(1 BYTE)                DEFAULT 'Y',
  BD_USE_TERMYN     CHAR(1 BYTE)                DEFAULT 'N',
  BD_USE_SDT        VARCHAR2(30 BYTE)           DEFAULT NULL,
  BD_USE_EDT        VARCHAR2(30 BYTE)           DEFAULT NULL,
  FILE_ID           VARCHAR2(39 BYTE)           DEFAULT NULL,
  GROUP_CODE        VARCHAR2(60 BYTE)           DEFAULT NULL,
  BD_THUMB1         VARCHAR2(300 BYTE)          DEFAULT NULL,
  BD_THUMB2         VARCHAR2(300 BYTE)          DEFAULT NULL,
  BD_THUMB3         VARCHAR2(300 BYTE)          DEFAULT NULL,
  BD_THUMB1_ALT     VARCHAR2(1500 BYTE)         DEFAULT NULL,
  BD_THUMB2_ALT     VARCHAR2(1500 BYTE)         DEFAULT NULL,
  BD_THUMB3_ALT     VARCHAR2(1500 BYTE)         DEFAULT NULL,
  BD_ANSWER         CLOB						DEFAULT NULL,
  BD_ANSWER_WRITER  VARCHAR2(60 BYTE)           DEFAULT NULL,
  BD_MOVIE          VARCHAR2(300 BYTE)          DEFAULT NULL,
  BD_HOW_MOVIE      CHAR(3 BYTE)                DEFAULT '0',
  BD_SCH_SDT        VARCHAR2(20 BYTE)			DEFAULT NULL,
  BD_SCH_EDT        VARCHAR2(20 BYTE)			DEFAULT NULL,
  BD_SECRET         CHAR(1 BYTE)                DEFAULT 'N',
  BD_IP             VARCHAR2(180 BYTE)          DEFAULT NULL,
  BD_REIDX          NUMBER(20)                  DEFAULT NULL,
  BD_RELEVEL        NUMBER(6)                   DEFAULT NULL,
  BD_REORDER        NUMBER(6)                   DEFAULT NULL,
  BD_KOGLUSEYN      CHAR(1 BYTE)                DEFAULT 'N',
  BD_KOGLTYPE1      VARCHAR2(150 BYTE)          DEFAULT NULL,
  BD_KOGLTYPE2      VARCHAR2(150 BYTE)          DEFAULT NULL,
  BD_PHONE          VARCHAR2(60 BYTE)           DEFAULT NULL,
  BD_MOBILE         VARCHAR2(60 BYTE)           DEFAULT NULL,
  BD_EMAIL          VARCHAR2(300 BYTE)          DEFAULT NULL,
  BD_ADDR1          VARCHAR2(300 BYTE)          DEFAULT NULL,
  BD_ADDR2          VARCHAR2(300 BYTE)          DEFAULT NULL,
  BD_EXT1          	VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT2          	VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT3          	VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT4          	VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT5          	VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT6          	VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT7          	VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT8          	VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT9          	VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT10          VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT11          VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT12          VARCHAR2(4000 BYTE)         DEFAULT NULL,
  REGDT             DATE                		DEFAULT SYSDATE               NOT NULL,
  UPDDT             DATE                		DEFAULT SYSDATE               NOT NULL,
  DELDT             DATE                        DEFAULT NULL,
  REGMEMID          VARCHAR2(60 BYTE)           DEFAULT NULL,
  UPDMEMID          VARCHAR2(60 BYTE)           DEFAULT NULL,
  DELMEMID          VARCHAR2(60 BYTE)           DEFAULT NULL,
  DELYN             CHAR(1 BYTE)                DEFAULT 'N'
);
COMMENT ON TABLE T_BOARD IS '공통게시판';
COMMENT ON COLUMN T_BOARD.BD_IDX IS '게시물인덱스';
COMMENT ON COLUMN T_BOARD.BC_ID IS '게시판아이디';
COMMENT ON COLUMN T_BOARD.BD_CODE IS '카테고리';
COMMENT ON COLUMN T_BOARD.BD_WRITER IS '작성자명';
COMMENT ON COLUMN T_BOARD.BD_TITLE IS '제목';
COMMENT ON COLUMN T_BOARD.BD_CONTENT IS '내용';
COMMENT ON COLUMN T_BOARD.BD_CONTENT_TEXT IS '내용텍스트';
COMMENT ON COLUMN T_BOARD.BD_READNUM IS '조회수';
COMMENT ON COLUMN T_BOARD.BD_PASSWD IS '비밀번호';
COMMENT ON COLUMN T_BOARD.BD_HTMLYN IS '컨텐츠 HTML사용YN';
COMMENT ON COLUMN T_BOARD.BD_SECRET IS '비밀글';
COMMENT ON COLUMN T_BOARD.BD_NOTICE IS '공지글';
COMMENT ON COLUMN T_BOARD.BD_NOTICE_TERMYN IS '공지여부 기간사용YN';
COMMENT ON COLUMN T_BOARD.BD_NOTICE_SDT IS '공지 시작일';
COMMENT ON COLUMN T_BOARD.BD_NOTICE_EDT IS '공지 종료일';
COMMENT ON COLUMN T_BOARD.BD_USEYN IS '게시여부';
COMMENT ON COLUMN T_BOARD.BD_USE_TERMYN IS '게시여부 기간사용YN';
COMMENT ON COLUMN T_BOARD.BD_USE_SDT IS '게시 시작일';
COMMENT ON COLUMN T_BOARD.BD_USE_EDT IS '게시 종료일';
COMMENT ON COLUMN T_BOARD.BD_IP IS '아이피';
COMMENT ON COLUMN T_BOARD.BD_REIDX IS '답변글인덱스';
COMMENT ON COLUMN T_BOARD.BD_RELEVEL IS '답변글레벨';
COMMENT ON COLUMN T_BOARD.BD_REORDER IS '답변글순서';
COMMENT ON COLUMN T_BOARD.FILE_ID IS '첨부파일 ID';
COMMENT ON COLUMN T_BOARD.GROUP_CODE IS '부서코드';
COMMENT ON COLUMN T_BOARD.BD_THUMB1 IS '썸네일1';
COMMENT ON COLUMN T_BOARD.BD_THUMB2 IS '썸네일2';
COMMENT ON COLUMN T_BOARD.BD_THUMB3 IS '썸네일3';
COMMENT ON COLUMN T_BOARD.BD_THUMB1_ALT IS '썸네일1 대체텍스트';
COMMENT ON COLUMN T_BOARD.BD_THUMB2_ALT IS '썸네일2 대체텍스트';
COMMENT ON COLUMN T_BOARD.BD_THUMB3_ALT IS '썸네일3 대체텍스트';
COMMENT ON COLUMN T_BOARD.BD_ANSWER IS '답변내용';
COMMENT ON COLUMN T_BOARD.BD_ANSWER_WRITER IS '답변 등록자';
COMMENT ON COLUMN T_BOARD.BD_MOVIE IS '동영상';
COMMENT ON COLUMN T_BOARD.BD_HOW_MOVIE IS '동영상 업로드 방식';
COMMENT ON COLUMN T_BOARD.BD_SCH_SDT IS '스케줄시작일(달력)';
COMMENT ON COLUMN T_BOARD.BD_SCH_EDT IS '스케줄종료일(달력)';
COMMENT ON COLUMN T_BOARD.BD_KOGLUSEYN IS '공공누리사용여부';
COMMENT ON COLUMN T_BOARD.BD_KOGLTYPE1 IS '공공누리타입1';
COMMENT ON COLUMN T_BOARD.BD_KOGLTYPE2 IS '공공누리타입2';
COMMENT ON COLUMN T_BOARD.BD_PHONE IS '전화번호';
COMMENT ON COLUMN T_BOARD.BD_MOBILE IS '휴대폰번호';
COMMENT ON COLUMN T_BOARD.BD_EMAIL IS '이메일주소';
COMMENT ON COLUMN T_BOARD.BD_ADDR1 IS '주소1';
COMMENT ON COLUMN T_BOARD.BD_ADDR2 IS '주소2';
COMMENT ON COLUMN T_BOARD.BD_EXT1 IS '확장컬럼1';
COMMENT ON COLUMN T_BOARD.BD_EXT2 IS '확장컬럼1';
COMMENT ON COLUMN T_BOARD.BD_EXT3 IS '확장컬럼1';
COMMENT ON COLUMN T_BOARD.BD_EXT4 IS '확장컬럼1';
COMMENT ON COLUMN T_BOARD.BD_EXT5 IS '확장컬럼1';
COMMENT ON COLUMN T_BOARD.BD_EXT6 IS '확장컬럼1';
COMMENT ON COLUMN T_BOARD.BD_EXT7 IS '확장컬럼1';
COMMENT ON COLUMN T_BOARD.BD_EXT8 IS '확장컬럼1';
COMMENT ON COLUMN T_BOARD.BD_EXT9 IS '확장컬럼1';
COMMENT ON COLUMN T_BOARD.BD_EXT10 IS '확장컬럼10';
COMMENT ON COLUMN T_BOARD.BD_EXT11 IS '확장컬럼11';
COMMENT ON COLUMN T_BOARD.BD_EXT12 IS '확장컬럼12';
COMMENT ON COLUMN T_BOARD.REGDT IS '작성일';
COMMENT ON COLUMN T_BOARD.UPDDT IS '수정일';
COMMENT ON COLUMN T_BOARD.DELDT IS '삭제일';
COMMENT ON COLUMN T_BOARD.REGMEMID IS '작성자아이디';
COMMENT ON COLUMN T_BOARD.UPDMEMID IS '수정자아이디';
COMMENT ON COLUMN T_BOARD.DELMEMID IS '삭제자아이디';
COMMENT ON COLUMN T_BOARD.DELYN IS '삭제여부';

INSERT INTO T_BOARD (
  BD_IDX            ,
  BC_ID             ,
  BD_CODE           ,
  BD_WRITER         ,
  BD_TITLE          ,
  BD_CONTENT        ,
  BD_CONTENT_TEXT   ,
  BD_READNUM        ,
  BD_PASSWD         ,
  BD_NOTICE         ,
  BD_NOTICE_TERMYN  ,
  BD_NOTICE_SDT     ,
  BD_NOTICE_EDT     ,
  BD_USEYN          ,
  BD_USE_TERMYN     ,
  BD_USE_SDT        ,
  BD_USE_EDT        ,
  FILE_ID           ,
  GROUP_CODE        ,
  BD_THUMB1         ,
  BD_THUMB2         ,
  BD_THUMB3         ,
  BD_THUMB1_ALT     ,
  BD_THUMB2_ALT     ,
  BD_THUMB3_ALT     ,
  BD_ANSWER         ,
  BD_ANSWER_WRITER  ,
  BD_MOVIE          ,
  BD_HOW_MOVIE      ,
  BD_SCH_SDT        ,
  BD_SCH_EDT		,
  BD_SECRET         ,
  BD_IP             ,
  BD_REIDX          ,
  BD_RELEVEL        ,
  BD_REORDER        ,
  BD_KOGLUSEYN      ,
  BD_KOGLTYPE1      ,
  BD_KOGLTYPE2      ,
  BD_PHONE          ,
  BD_MOBILE         ,
  BD_EMAIL          ,
  BD_ADDR1          ,
  BD_ADDR2          ,
  BD_EXT1			,
  BD_EXT2			,
  BD_EXT3			,
  BD_EXT4			,
  BD_EXT5			,
  BD_EXT6			,
  BD_EXT7			,
  BD_EXT8			,
  BD_EXT9			,
  BD_EXT10			,
  BD_EXT11			,
  BD_EXT12			,
  REGDT             ,
  UPDDT             ,
  DELDT             ,
  REGMEMID          ,
  UPDMEMID          ,
  DELMEMID          ,
  DELYN
    )
SELECT
  BD_IDX			,
  BC_ID             ,
  BD_CODE           ,
  BD_WRITER         ,
  BD_TITLE          ,
  BD_CONTENT        ,
  BD_CONTENT        ,
  BD_READNUM        ,
  BD_PASSWD         ,
  BD_NOTICE         ,
  BD_NOTICE_TERMYN  ,
  BD_NOTICE_SDT     ,
  BD_NOTICE_EDT     ,
  BD_USEYN          ,
  BD_USE_TERMYN     ,
  BD_USE_SDT        ,
  BD_USE_EDT        ,
  FILE_ID           ,
  GROUP_CODE        ,
  BD_THUMB1         ,
  BD_THUMB2         ,
  BD_THUMB3         ,
  BD_THUMB1_ALT     ,
  BD_THUMB2_ALT     ,
  BD_THUMB3_ALT     ,
  BD_ANSWER         ,
  BD_ANSWER_WRITER  ,
  BD_MOVIE          ,
  BD_HOW_MOVIE      ,
  BD_SCH_SDT        ,
  BD_SCH_EDT		,
  BD_SECRET         ,
  BD_IP             ,
  BD_REIDX          ,
  BD_RELEVEL        ,
  BD_REORDER        ,
  BD_KOGLUSEYN      ,
  BD_KOGLTYPE1      ,
  BD_KOGLTYPE2      ,
  BD_PHONE          ,
  BD_MOBILE         ,
  BD_EMAIL          ,
  BD_ADDR1          ,
  BD_ADDR2          ,
  BD_EXT1			,
  BD_EXT2			,
  BD_EXT3			,
  BD_EXT4			,
  BD_EXT5			,
  BD_EXT6			,
  BD_EXT7			,
  BD_EXT8			,
  BD_EXT9			,
  BD_EXT10			,
  BD_EXT11			,
  BD_EXT12			,
  REGDT             ,
  UPDDT             ,
  DELDT             ,
  REGMEMID          ,
  UPDMEMID          ,
  DELMEMID          ,
  DELYN
  FROM T_BOARD_;

DROP SEQUENCE T_BOARD_SEQ;
BEGIN
DECLARE seqVal NUMBER;
    BEGIN
        SELECT MAX(nvl(bd_idx,0))+1
        INTO seqval
        FROM t_board;
        execute immediate('CREATE SEQUENCE T_BOARD_SEQ START WITH '||seqVal||' INCREMENT BY 1');
      END;
END;

DROP TABLE T_BOARD_ CASCADE CONSTRAINTS;
ALTER TABLE T_BOARD ADD CONSTRAINT T_BOARD_PK PRIMARY KEY (BD_IDX);
CREATE INDEX T_BOARD_BCID ON T_BOARD( BC_ID );
update t_board a set bd_htmlyn = (select bc_editoryn from t_board_config b where B.BC_ID = A.BC_ID);