{
    "view_title": "ドキュメントビューアー",
    "page_total": "全 ",
    "msg_exception_url_access_failed": "現在アクセスしたURLは、アクセス権限がないか、存在しないファイルです。",
    "msg_archiveFile_convFail" : "圧縮ファイル変換に失敗したか、サポートされていない圧縮ファイル形式です。",
    "help.erro_code.errorcode.2.desc1": "変換できないファイルです。",
    "help.erro_code.errorcode.3.desc1": "暗号化された文書は変換できません。",
    "help.erro_code.errorcode.4.desc1": "DRMがかかった文書は変換できません。",
    "help.erro_code.errorcode.22.desc1": "変換できるアーカイブファイルの最大サイズは500 MBです。",
    "help.erro_code.errorcode.101.desc1": "IMAGE変換に失敗しました。",
    "help.erro_code.errorcode.134.desc1": "メモリが不足してIMAGE変換が失敗しました。<br/>管理者にお問い合わせください。",
    "help.erro_code.errorcode.254.desc1": "製品のライセンスが終了しました。",
    "help.erro_code.errorcode.255.desc1": "不明なエラー",
    "msg_sheet_convFail": "シートを開けませんでした。",
    "msg_input_password": "文書のパスワードを入力してください",
    "msg_exception_open_failed": "ドキュメントを開くに失敗しました。 <br>再試行するには、更新をしてください。",
    "msg_input_retry": "入力されたパスワードが正しくありません",
    "msg_refresh": "更新",
    "msg_exception_doc": "このドキュメントはパスワードで保護されています。<br />ドキュメントを編集するにはパスワードを入力してください。",
    "msg_cancel": "キャンセル",
    "msg_submit": "確認する",
    "msg_download": "ダウンロード",
    "msg_light_backgroundcolor": "明るい背景に切り替える",
    "msg_dark_backgroundcolor": "暗い背景に切り替える",
    "msg_window_close": "ウィンドウを閉じる",
    "msg_save_annotation": "注釈を保存",
    "msg_fail_save_annotation": "アノテーションの保存に失敗",
    "msg_delete_marker": "すべてのマーカーを削除してもよろしいですか?",
    "msg_delete_selected_marker": "選択したマーカーを削除してもよろしいですか?",
    "msg_delete_selected_memo": "メモを削除してもよろしいですか?",
    "icon_thumbnail_open": "サムネール表示",
    "icon_thumbnail_close": "サムネール表示解除",
    "icon_thumbnail_drag": "サムネイルをドラッグ",
    "icon_download": "ダウンロード",
    "icon_more": "もっと",
    "icon_fullscreen_open": "全画面表示",
    "icon_fullscreen_close": "全画面解除",
    "icon_first_sheet": "先頭シートへ",
    "icon_prev_sheet": "前のシートへ",
    "icon_next_sheet": "次のシートへ",
    "icon_end_sheet": "最後シートへ",
    "icon_prev_page": "前のページへ",
    "icon_next_page": "次のページへ",
    "icon_prev": "前の",
    "icon_next": "次の",
    "icon_rotate_clockwise": "時計回りに回転",
    "icon_zoomin": "拡大",
    "icon_zoomout": "縮小",
    "icon_originsize": "オリジナルサイズ",
    "icon_pagefit": "画面にフィット",
    "icon_pagewidthfit": "画面の幅に合わせる",
    "icon_move_page_open": "ページを選択",
    "icon_move_sheet_open": "シートを選択",
    "icon_backgroundcolor":"背景色を変更する",
    "icon_search": "テキスト検索",
    "icon_marker": "マーカー", 
    "icon_save_annotation": "注釈を保存",
    "icon_marker_color": "色",
    "icon_marker_thickness": "厚さ", 
    "icon_delete_marker": "すべてのマーカーを削除",
    "icon_text_highlight": "ハイライト",
    "icon_memo": "メモを追加",
    "icon_delete_memo": "削除する",
    "hightlight_color_yellow": "黄",
    "hightlight_color_green": "緑",
    "hightlight_color_blue": "空色",
    "hightlight_color_pink": "ピンク",
    "hightlight_color_none": "削除する",
    "info_company_name":"会社/機関",
    "info_product_name_version_key":"製品 Version",
    "info_product_name_version_value":"Synap Document Viewer 2019",
    "into_product_copyright":"Copyright ⓒ Synapsoft Corp. All rights reserved.",
    "info_menu": "情報",
    "sns_title": "共有",
    "sns_url_copy": "URL コピー",
    "sns_url_select": "URL 選択",
    "sns_url_copy_completed": "URLがコピーされました。",
    "print_menu": "印刷",
    "dialog":"通知ボックス",
    "dialog_logo":"会社のロゴ",
    "dialog-passwd":"パスワード、入力フィールド",
    "input-searchword": "検索語を入力",
    "input_limit_searchword": "検索語を10文字以内で入力してください",
    "empty-searchword": "検索語が見つかりません。",
    "none_move_search": "前/次の検索結果はありません。",
    "input_author": "著者"
}