--
-- J_ATTACHFILE  (Table)
--
CREATE TABLE J_ATTACHFILE
(
  FILE_IDX              NUMBER(22)              DEFAULT 0                     NOT NULL,
  FILE_ID               VARCHAR2(39 BYTE)       NOT NULL,
  FILE_SEQ              NUMBER(22)              NOT NULL,
  FILE_NAME             VARCHAR2(300 BYTE)      NOT NULL,
  FILE_SIZE             NUMBER(22)              DEFAULT NULL,
  FILE_FOLDER           VARCHAR2(300 BYTE)      DEFAULT NULL,
  FILE_MASK             VARCHAR2(300 BYTE)      DEFAULT NULL,
  DOWNLOAD_COUNT        NUMBER(22)              DEFAULT NULL,
  DOWNLOAD_EXPIRE_DATE  VARCHAR2(24 BYTE)       DEFAULT NULL,
  DOWNLOAD_LIMIT_COUNT  NUMBER(22)              DEFAULT NULL,
  REG_DATE              DATE                    DEFAULT SYSDATE,
  DELETE_YN             VARCHAR2(1 BYTE)        DEFAULT 'Y'
);

COMMENT ON TABLE J_ATTACHFILE IS '첨부파일관리';

COMMENT ON COLUMN J_ATTACHFILE.FILE_IDX IS '파일인덱스';

COMMENT ON COLUMN J_ATTACHFILE.FILE_ID IS '파일ID';

COMMENT ON COLUMN J_ATTACHFILE.FILE_SEQ IS '파일SEQ';

COMMENT ON COLUMN J_ATTACHFILE.FILE_NAME IS '파일원본이름';

COMMENT ON COLUMN J_ATTACHFILE.FILE_SIZE IS '파일용량';

COMMENT ON COLUMN J_ATTACHFILE.FILE_FOLDER IS '파일저장폴더';

COMMENT ON COLUMN J_ATTACHFILE.FILE_MASK IS '파일저장이름';

COMMENT ON COLUMN J_ATTACHFILE.DOWNLOAD_COUNT IS '파일다운로드수';

COMMENT ON COLUMN J_ATTACHFILE.DOWNLOAD_EXPIRE_DATE IS '파일다운로드기한';

COMMENT ON COLUMN J_ATTACHFILE.DOWNLOAD_LIMIT_COUNT IS '파일다운로드제한수';

COMMENT ON COLUMN J_ATTACHFILE.REG_DATE IS '파일등록일';

COMMENT ON COLUMN J_ATTACHFILE.DELETE_YN IS '파일삭제여부';


--
-- T_BOARD  (Table)
--
CREATE TABLE T_BOARD
(
  BD_IDX            NUMBER(20)                  DEFAULT '0'                   NOT NULL,
  BC_ID             VARCHAR2(60 BYTE)           DEFAULT NULL,
  BD_CODE           VARCHAR2(60 BYTE)           DEFAULT NULL,
  BD_WRITER         VARCHAR2(60 BYTE)           DEFAULT NULL,
  BD_TITLE          VARCHAR2(300 BYTE)          DEFAULT NULL,
  BD_CONTENT        CLOB                        DEFAULT NULL,
  BD_CONTENT_TEXT   CLOB                        DEFAULT NULL,
  BD_READNUM        NUMBER(11)                  DEFAULT 0,
  BD_PASSWD         VARCHAR2(300 BYTE)          DEFAULT NULL,
  BD_HTMLYN         CHAR(1 BYTE)                DEFAULT 'N',
  BD_NOTICE         CHAR(1 BYTE)                DEFAULT '0',
  BD_NOTICE_TERMYN  CHAR(1 BYTE)                DEFAULT 'N',
  BD_NOTICE_SDT     VARCHAR2(30 BYTE)           DEFAULT NULL,
  BD_NOTICE_EDT     VARCHAR2(30 BYTE)           DEFAULT NULL,
  BD_USEYN          CHAR(1 BYTE)                DEFAULT 'Y',
  BD_USE_TERMYN     CHAR(1 BYTE)                DEFAULT 'N',
  BD_USE_SDT        VARCHAR2(30 BYTE)           DEFAULT NULL,
  BD_USE_EDT        VARCHAR2(30 BYTE)           DEFAULT NULL,
  FILE_ID           VARCHAR2(39 BYTE)           DEFAULT NULL,
  GROUP_CODE        VARCHAR2(60 BYTE)           DEFAULT NULL,
  BD_THUMB1         VARCHAR2(300 BYTE)          DEFAULT NULL,
  BD_THUMB2         VARCHAR2(300 BYTE)          DEFAULT NULL,
  BD_THUMB3         VARCHAR2(300 BYTE)          DEFAULT NULL,
  BD_THUMB1_ALT     VARCHAR2(1500 BYTE)         DEFAULT NULL,
  BD_THUMB2_ALT     VARCHAR2(1500 BYTE)         DEFAULT NULL,
  BD_THUMB3_ALT     VARCHAR2(1500 BYTE)         DEFAULT NULL,
  BD_ANSWER         CLOB                        DEFAULT NULL,
  BD_ANSWER_WRITER  VARCHAR2(60 BYTE)           DEFAULT NULL,
  BD_MOVIE          VARCHAR2(300 BYTE)          DEFAULT NULL,
  BD_HOW_MOVIE      CHAR(3 BYTE)                DEFAULT '0',
  BD_SCH_SDT        VARCHAR2(20 BYTE)           DEFAULT NULL,
  BD_SCH_EDT        VARCHAR2(20 BYTE)           DEFAULT NULL,
  BD_SECRET         CHAR(1 BYTE)                DEFAULT 'N',
  BD_IP             VARCHAR2(180 BYTE)          DEFAULT NULL,
  BD_REIDX          NUMBER(20)                  DEFAULT NULL,
  BD_RELEVEL        NUMBER(6)                   DEFAULT NULL,
  BD_REORDER        NUMBER(6)                   DEFAULT NULL,
  BD_KOGLUSEYN      CHAR(1 BYTE)                DEFAULT 'N',
  BD_KOGLTYPE1      VARCHAR2(150 BYTE)          DEFAULT NULL,
  BD_KOGLTYPE2      VARCHAR2(150 BYTE)          DEFAULT NULL,
  BD_PHONE          VARCHAR2(60 BYTE)           DEFAULT NULL,
  BD_MOBILE         VARCHAR2(60 BYTE)           DEFAULT NULL,
  BD_EMAIL          VARCHAR2(300 BYTE)          DEFAULT NULL,
  BD_ADDR1          VARCHAR2(300 BYTE)          DEFAULT NULL,
  BD_ADDR2          VARCHAR2(300 BYTE)          DEFAULT NULL,
  BD_EXT1           VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT2           VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT3           VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT4           VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT5           VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT6           VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT7           VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT8           VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT9           VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT10          VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT11          VARCHAR2(4000 BYTE)         DEFAULT NULL,
  BD_EXT12          VARCHAR2(4000 BYTE)         DEFAULT NULL,
  REGDT             DATE                        DEFAULT SYSDATE               NOT NULL,
  UPDDT             DATE                        DEFAULT SYSDATE               NOT NULL,
  DELDT             DATE                        DEFAULT NULL,
  REGMEMID          VARCHAR2(60 BYTE)           DEFAULT NULL,
  UPDMEMID          VARCHAR2(60 BYTE)           DEFAULT NULL,
  DELMEMID          VARCHAR2(60 BYTE)           DEFAULT NULL,
  DELYN             CHAR(1 BYTE)                DEFAULT 'N'
);

COMMENT ON TABLE T_BOARD IS '공통게시판';

COMMENT ON COLUMN T_BOARD.BD_IDX IS '게시물인덱스';

COMMENT ON COLUMN T_BOARD.BC_ID IS '게시판아이디';

COMMENT ON COLUMN T_BOARD.BD_CODE IS '카테고리';

COMMENT ON COLUMN T_BOARD.BD_WRITER IS '작성자명';

COMMENT ON COLUMN T_BOARD.BD_TITLE IS '제목';

COMMENT ON COLUMN T_BOARD.BD_CONTENT IS '내용';

COMMENT ON COLUMN T_BOARD.BD_CONTENT_TEXT IS '내용텍스트';

COMMENT ON COLUMN T_BOARD.BD_READNUM IS '조회수';

COMMENT ON COLUMN T_BOARD.BD_PASSWD IS '비밀번호';

COMMENT ON COLUMN T_BOARD.BD_HTMLYN IS '컨텐츠 HTML사용YN';

COMMENT ON COLUMN T_BOARD.BD_NOTICE IS '공지글';

COMMENT ON COLUMN T_BOARD.BD_NOTICE_TERMYN IS '공지여부 기간사용YN';

COMMENT ON COLUMN T_BOARD.BD_NOTICE_SDT IS '공지 시작일';

COMMENT ON COLUMN T_BOARD.BD_NOTICE_EDT IS '공지 종료일';

COMMENT ON COLUMN T_BOARD.BD_USEYN IS '게시여부';

COMMENT ON COLUMN T_BOARD.BD_USE_TERMYN IS '게시여부 기간사용YN';

COMMENT ON COLUMN T_BOARD.BD_USE_SDT IS '게시 시작일';

COMMENT ON COLUMN T_BOARD.BD_USE_EDT IS '게시 종료일';

COMMENT ON COLUMN T_BOARD.FILE_ID IS '첨부파일 ID';

COMMENT ON COLUMN T_BOARD.GROUP_CODE IS '부서코드';

COMMENT ON COLUMN T_BOARD.BD_THUMB1 IS '썸네일1';

COMMENT ON COLUMN T_BOARD.BD_THUMB2 IS '썸네일2';

COMMENT ON COLUMN T_BOARD.BD_THUMB3 IS '썸네일3';

COMMENT ON COLUMN T_BOARD.BD_THUMB1_ALT IS '썸네일1 대체텍스트';

COMMENT ON COLUMN T_BOARD.BD_THUMB2_ALT IS '썸네일2 대체텍스트';

COMMENT ON COLUMN T_BOARD.BD_THUMB3_ALT IS '썸네일3 대체텍스트';

COMMENT ON COLUMN T_BOARD.BD_ANSWER IS '답변내용';

COMMENT ON COLUMN T_BOARD.BD_ANSWER_WRITER IS '답변 등록자';

COMMENT ON COLUMN T_BOARD.BD_MOVIE IS '동영상';

COMMENT ON COLUMN T_BOARD.BD_HOW_MOVIE IS '동영상 업로드 방식';

COMMENT ON COLUMN T_BOARD.BD_SCH_SDT IS '스케줄시작일(달력)';

COMMENT ON COLUMN T_BOARD.BD_SCH_EDT IS '스케줄종료일(달력)';

COMMENT ON COLUMN T_BOARD.BD_SECRET IS '비밀글';

COMMENT ON COLUMN T_BOARD.BD_IP IS '아이피';

COMMENT ON COLUMN T_BOARD.BD_REIDX IS '답변글인덱스';

COMMENT ON COLUMN T_BOARD.BD_RELEVEL IS '답변글레벨';

COMMENT ON COLUMN T_BOARD.BD_REORDER IS '답변글순서';

COMMENT ON COLUMN T_BOARD.BD_KOGLUSEYN IS '공공누리사용여부';

COMMENT ON COLUMN T_BOARD.BD_KOGLTYPE1 IS '공공누리타입1';

COMMENT ON COLUMN T_BOARD.BD_KOGLTYPE2 IS '공공누리타입2';

COMMENT ON COLUMN T_BOARD.BD_PHONE IS '전화번호';

COMMENT ON COLUMN T_BOARD.BD_MOBILE IS '휴대폰번호';

COMMENT ON COLUMN T_BOARD.BD_EMAIL IS '이메일주소';

COMMENT ON COLUMN T_BOARD.BD_ADDR1 IS '주소1';

COMMENT ON COLUMN T_BOARD.BD_ADDR2 IS '주소2';

COMMENT ON COLUMN T_BOARD.BD_EXT1 IS '확장컬럼1';

COMMENT ON COLUMN T_BOARD.BD_EXT2 IS '확장컬럼1';

COMMENT ON COLUMN T_BOARD.BD_EXT3 IS '확장컬럼1';

COMMENT ON COLUMN T_BOARD.BD_EXT4 IS '확장컬럼1';

COMMENT ON COLUMN T_BOARD.BD_EXT5 IS '확장컬럼1';

COMMENT ON COLUMN T_BOARD.BD_EXT6 IS '확장컬럼1';

COMMENT ON COLUMN T_BOARD.BD_EXT7 IS '확장컬럼1';

COMMENT ON COLUMN T_BOARD.BD_EXT8 IS '확장컬럼1';

COMMENT ON COLUMN T_BOARD.BD_EXT9 IS '확장컬럼1';

COMMENT ON COLUMN T_BOARD.BD_EXT10 IS '확장컬럼10';

COMMENT ON COLUMN T_BOARD.BD_EXT11 IS '확장컬럼11';

COMMENT ON COLUMN T_BOARD.BD_EXT12 IS '확장컬럼12';

COMMENT ON COLUMN T_BOARD.REGDT IS '작성일';

COMMENT ON COLUMN T_BOARD.UPDDT IS '수정일';

COMMENT ON COLUMN T_BOARD.DELDT IS '삭제일';

COMMENT ON COLUMN T_BOARD.REGMEMID IS '작성자아이디';

COMMENT ON COLUMN T_BOARD.UPDMEMID IS '수정자아이디';

COMMENT ON COLUMN T_BOARD.DELMEMID IS '삭제자아이디';

COMMENT ON COLUMN T_BOARD.DELYN IS '삭제여부';



--
-- T_BOARD_CONFIG  (Table)
--
CREATE TABLE T_BOARD_CONFIG
(
  BC_ID             VARCHAR2(150 BYTE)          NOT NULL,
  BC_NAME           VARCHAR2(300 BYTE)          DEFAULT NULL,
  BC_SKIN           VARCHAR2(60 BYTE)           DEFAULT NULL,
  BC_TYPE           CHAR(1 BYTE)                DEFAULT '1',
  BC_TOPINFO        VARCHAR2(765 BYTE)          DEFAULT NULL,
  BC_VIEWCOUNT      NUMBER(6)                   DEFAULT NULL,
  BC_DEFAULTPAGE    VARCHAR2(150 BYTE)          DEFAULT NULL,
  BC_LIST           VARCHAR2(30 BYTE)           DEFAULT '100',
  BC_VIEW           VARCHAR2(30 BYTE)           DEFAULT '100',
  BC_REGIST         VARCHAR2(30 BYTE)           DEFAULT '900',
  BC_UPDATE         VARCHAR2(30 BYTE)           DEFAULT '900',
  BC_REPLY          VARCHAR2(30 BYTE)           DEFAULT '900',
  BC_MNGR_LIST      VARCHAR2(30 BYTE)           DEFAULT NULL,
  BC_MNGR_VIEW      VARCHAR2(30 BYTE)           DEFAULT NULL,
  BC_MNGR_REGIST    VARCHAR2(30 BYTE)           DEFAULT NULL,
  BC_MNGR_UPDATE    VARCHAR2(30 BYTE)           DEFAULT NULL,
  BC_MNGR_REPLY     VARCHAR2(30 BYTE)           DEFAULT NULL,
  BC_REPLYYN        CHAR(1 BYTE)                DEFAULT NULL,
  BC_SECRETYN       CHAR(1 BYTE)                DEFAULT NULL,
  BC_NOTICEYN       CHAR(1 BYTE)                DEFAULT NULL,
  BC_EDITORYN       CHAR(1 BYTE)                DEFAULT NULL,
  BC_PREVNEXTYN     CHAR(1 BYTE)                DEFAULT NULL,
  BC_KOGLYN         CHAR(1 BYTE)                DEFAULT NULL,
  BC_COMMENT        NUMBER(11)                  DEFAULT 0,
  BC_RSS            CHAR(1 BYTE)                DEFAULT NULL,
  BC_GROUPYN        CHAR(1 BYTE)                DEFAULT NULL,
  BC_GROUPCODE      VARCHAR2(60 BYTE)           DEFAULT NULL,
  BC_FILEYN         CHAR(1 BYTE)                DEFAULT NULL,
  BC_FILECOUNT      NUMBER(6)                   DEFAULT NULL,
  BC_FILESIZE       NUMBER(6)                   DEFAULT NULL,
  BC_FILETYPEDESC   VARCHAR2(300 BYTE)          DEFAULT 'all',
  BC_THUMBYN        CHAR(1 BYTE)                DEFAULT NULL,
  BC_THUMBCOUNT     NUMBER(6)                   DEFAULT 1,
  BC_THUMBWIDTH     NUMBER(6)                   DEFAULT NULL,
  BC_THUMBHEIGHT    NUMBER(6)                   DEFAULT NULL,
  BC_THUMBRATIOYN   CHAR(1 BYTE)                DEFAULT NULL,
  BC_EXTCOLUMNINFO  VARCHAR2(4000 BYTE)         DEFAULT NULL,
  REGDT             DATE                        DEFAULT SYSDATE               NOT NULL,
  UPDDT             DATE                        DEFAULT SYSDATE               NOT NULL,
  DELDT             DATE                        DEFAULT NULL,
  REGMEMID          VARCHAR2(60 BYTE)           DEFAULT NULL,
  UPDMEMID          VARCHAR2(60 BYTE)           DEFAULT NULL,
  DELMEMID          VARCHAR2(60 BYTE)           DEFAULT NULL,
  DELYN             CHAR(1 BYTE)                DEFAULT NULL
);

COMMENT ON TABLE T_BOARD_CONFIG IS '게시판설정관리';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_ID IS '게시판아이디';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_NAME IS '게시판이름';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_SKIN IS '게시판스킨';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_TYPE IS '게시판유형(1공통.2커스텀)';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_TOPINFO IS '상단정보';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_VIEWCOUNT IS '게시물갯수';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_DEFAULTPAGE IS '기본페이지(리스트,뷰)';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_LIST IS '목록권한';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_VIEW IS '조회권한';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_REGIST IS '등록권한';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_UPDATE IS '수정권한';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_REPLY IS '답변권한';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_MNGR_LIST IS '관리자 목록권한';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_MNGR_VIEW IS '관리자 조회권한';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_MNGR_REGIST IS '관리자 등록권한';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_MNGR_UPDATE IS '관리자 수정권한';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_MNGR_REPLY IS '관리자 답변권한';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_REPLYYN IS '답글사용여부';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_SECRETYN IS '비밀글사용여부';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_NOTICEYN IS '공지글사용여부';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_EDITORYN IS '에디터사용여부';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_PREVNEXTYN IS '이전/다음사용여부';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_KOGLYN IS '공공누리사용여부';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_COMMENT IS '댓글 사용어부';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_RSS IS 'RSS 사용 여부';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_GROUPYN IS '카테고리사용여부';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_GROUPCODE IS '카테고리코드';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_FILEYN IS '첨부사용여부';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_FILECOUNT IS '첨부갯수';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_FILESIZE IS '첨부용량';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_FILETYPEDESC IS '첨부파일 확장자 descripter';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_THUMBYN IS '썸네일사용여부';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_THUMBCOUNT IS '썸네일갯수';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_THUMBWIDTH IS '썸네일 가로사이즈';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_THUMBHEIGHT IS '썸네일 세로사이즈';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_THUMBRATIOYN IS '비율유지 Y유지N고정';

COMMENT ON COLUMN T_BOARD_CONFIG.BC_EXTCOLUMNINFO IS '확장컬럼정보';

COMMENT ON COLUMN T_BOARD_CONFIG.REGDT IS '등록일';

COMMENT ON COLUMN T_BOARD_CONFIG.UPDDT IS '수정일';

COMMENT ON COLUMN T_BOARD_CONFIG.DELDT IS '삭제일';

COMMENT ON COLUMN T_BOARD_CONFIG.REGMEMID IS '등록자아이디';

COMMENT ON COLUMN T_BOARD_CONFIG.UPDMEMID IS '수정자아이디';

COMMENT ON COLUMN T_BOARD_CONFIG.DELMEMID IS '삭제자아이디';

COMMENT ON COLUMN T_BOARD_CONFIG.DELYN IS '삭제여부';



--
-- T_BOARD_LOB  (Table)
--
CREATE TABLE T_BOARD_LOB
(
  BL_IDX       NUMBER(20)                       DEFAULT '0'                   NOT NULL,
  BD_IDX       NUMBER(20)                       NOT NULL,
  BL_COLUMN    VARCHAR2(60 BYTE)                DEFAULT NULL,
  BL_CONTENTS  CLOB                             DEFAULT NULL
);

COMMENT ON TABLE T_BOARD_LOB IS '게시판 LOB데이터 추가컬럼 테이블';

COMMENT ON COLUMN T_BOARD_LOB.BL_IDX IS '추가컬럼데이터인덱스';

COMMENT ON COLUMN T_BOARD_LOB.BD_IDX IS '게시글인덱스';

COMMENT ON COLUMN T_BOARD_LOB.BL_COLUMN IS '게시글컬럼';

COMMENT ON COLUMN T_BOARD_LOB.BL_CONTENTS IS '게시글내용';



--
-- T_CODE  (Table)
--
CREATE TABLE T_CODE
(
  C_CODE     VARCHAR2(150 BYTE)                 NOT NULL,
  C_NAME     VARCHAR2(150 BYTE)                 DEFAULT NULL,
  C_PCODE    VARCHAR2(60 BYTE)                  DEFAULT NULL,
  C_DEPTH    NUMBER(22)                         DEFAULT NULL,
  C_ORDER    NUMBER(22)                         DEFAULT NULL,
  C_AUTH     CHAR(2 BYTE)                       DEFAULT '00',
  DEFAULTYN  CHAR(1 BYTE)                       DEFAULT 'N',
  EXP1       VARCHAR2(1000 BYTE)                DEFAULT NULL,
  ETC1       VARCHAR2(150 BYTE)                 DEFAULT NULL,
  ETC2       VARCHAR2(300 BYTE)                 DEFAULT NULL,
  REGDT      DATE                               DEFAULT SYSDATE,
  UPDDT      DATE                               DEFAULT SYSDATE,
  DELDT      DATE                               DEFAULT NULL,
  REGMEMID   VARCHAR2(60 BYTE)                  DEFAULT NULL,
  UPDMEMID   VARCHAR2(60 BYTE)                  DEFAULT NULL,
  DELMEMID   VARCHAR2(60 BYTE)                  DEFAULT NULL,
  DELYN      CHAR(1 BYTE)                       DEFAULT 'N'
);

COMMENT ON TABLE T_CODE IS '코드관리';

COMMENT ON COLUMN T_CODE.C_CODE IS '코드';

COMMENT ON COLUMN T_CODE.C_NAME IS '코드명';

COMMENT ON COLUMN T_CODE.C_PCODE IS '부모코드';

COMMENT ON COLUMN T_CODE.C_DEPTH IS '뎁스';

COMMENT ON COLUMN T_CODE.C_ORDER IS '코드순서';

COMMENT ON COLUMN T_CODE.C_AUTH IS '목록권한';

COMMENT ON COLUMN T_CODE.DEFAULTYN IS '기본생성코드';

COMMENT ON COLUMN T_CODE.EXP1 IS '설명';

COMMENT ON COLUMN T_CODE.ETC1 IS '기타';

COMMENT ON COLUMN T_CODE.ETC2 IS '기타';

COMMENT ON COLUMN T_CODE.REGDT IS '등록일';

COMMENT ON COLUMN T_CODE.UPDDT IS '수정일';

COMMENT ON COLUMN T_CODE.DELDT IS '삭제일';

COMMENT ON COLUMN T_CODE.REGMEMID IS '등록자아이디';

COMMENT ON COLUMN T_CODE.UPDMEMID IS '수정자아이디';

COMMENT ON COLUMN T_CODE.DELMEMID IS '삭제자아이디';

COMMENT ON COLUMN T_CODE.DELYN IS '삭제여부';



--
-- T_COMEMBER  (Table)
--
CREATE TABLE T_COMEMBER
(
  COMEM_IDX          NUMBER(11)                 NOT NULL,
  COMEM_ID           VARCHAR2(60 BYTE)          DEFAULT NULL,
  COMEM_COMNO        VARCHAR2(36 BYTE)          DEFAULT NULL,
  COMEM_NAME         VARCHAR2(150 BYTE)         DEFAULT NULL,
  COMEM_CEONM        VARCHAR2(60 BYTE)          DEFAULT NULL,
  COMEM_CODE_TYPE    VARCHAR2(60 BYTE)          DEFAULT NULL,
  COMEM_CODE_CATE    VARCHAR2(60 BYTE)          DEFAULT NULL,
  COMEM_EMPL         VARCHAR2(15 BYTE)          DEFAULT NULL,
  COMEM_POST         VARCHAR2(18 BYTE)          DEFAULT NULL,
  COMEM_ADDR1        VARCHAR2(600 BYTE)         DEFAULT NULL,
  COMEM_ADDR2        VARCHAR2(600 BYTE)         DEFAULT NULL,
  COMEM_CHRGE_NAME   VARCHAR2(60 BYTE)          DEFAULT NULL,
  COMEM_CHRGE_GRP    VARCHAR2(60 BYTE)          DEFAULT NULL,
  COMEM_CHRGE_POS    VARCHAR2(60 BYTE)          DEFAULT NULL,
  COMEM_CHRGE_POST   VARCHAR2(18 BYTE)          DEFAULT NULL,
  COMEM_CHRGE_ADDR1  VARCHAR2(600 BYTE)         DEFAULT NULL,
  COMEM_CHRGE_ADDR2  VARCHAR2(600 BYTE)         DEFAULT NULL,
  COMEM_CHRGE_CELL   VARCHAR2(45 BYTE)          DEFAULT NULL,
  COMEM_CHRGE_TEL    VARCHAR2(55 BYTE)          DEFAULT NULL,
  COMEM_CHRGE_MAIL   VARCHAR2(300 BYTE)         DEFAULT NULL,
  COMEM_CHRGE_TNAME  VARCHAR2(60 BYTE)          DEFAULT NULL,
  COMEM_CHRGE_TMAIL  VARCHAR2(300 BYTE)         DEFAULT NULL,
  COMEM_STATUS       VARCHAR2(60 BYTE)          DEFAULT NULL,
  ETC1               VARCHAR2(150 BYTE)         DEFAULT NULL,
  ETC2               VARCHAR2(150 BYTE)         DEFAULT NULL,
  USEYN              CHAR(1 BYTE)               DEFAULT 'Y',
  REGDT              TIMESTAMP(6)               DEFAULT SYSDATE               NOT NULL,
  UPDDT              TIMESTAMP(6)               DEFAULT SYSDATE               NOT NULL,
  DELDT              DATE                       DEFAULT NULL,
  REGMEMID           VARCHAR2(60 BYTE)          DEFAULT NULL,
  UPDMEMID           VARCHAR2(60 BYTE)          DEFAULT NULL,
  DELMEMID           VARCHAR2(60 BYTE)          DEFAULT NULL,
  DELYN              CHAR(1 BYTE)               DEFAULT 'N'
);

COMMENT ON TABLE T_COMEMBER IS '기업정보';

COMMENT ON COLUMN T_COMEMBER.COMEM_IDX IS '기업인덱스';

COMMENT ON COLUMN T_COMEMBER.COMEM_ID IS '기업아이디';

COMMENT ON COLUMN T_COMEMBER.COMEM_COMNO IS '사업자등록번호';

COMMENT ON COLUMN T_COMEMBER.COMEM_NAME IS '기업명';

COMMENT ON COLUMN T_COMEMBER.COMEM_CEONM IS '대표자이름';

COMMENT ON COLUMN T_COMEMBER.COMEM_CODE_TYPE IS '업태';

COMMENT ON COLUMN T_COMEMBER.COMEM_CODE_CATE IS '업종';

COMMENT ON COLUMN T_COMEMBER.COMEM_EMPL IS '상시근로자수';

COMMENT ON COLUMN T_COMEMBER.COMEM_POST IS '우편번호(도로명)';

COMMENT ON COLUMN T_COMEMBER.COMEM_ADDR1 IS '주소(도로명)';

COMMENT ON COLUMN T_COMEMBER.COMEM_ADDR2 IS '주소 상세(도로명)';

COMMENT ON COLUMN T_COMEMBER.COMEM_CHRGE_NAME IS '담당자성명';

COMMENT ON COLUMN T_COMEMBER.COMEM_CHRGE_GRP IS '담당자부서';

COMMENT ON COLUMN T_COMEMBER.COMEM_CHRGE_POS IS '담당자직위';

COMMENT ON COLUMN T_COMEMBER.COMEM_CHRGE_POST IS '담당자 우편번호(도로명)';

COMMENT ON COLUMN T_COMEMBER.COMEM_CHRGE_ADDR1 IS '담당자 주소(도로명)';

COMMENT ON COLUMN T_COMEMBER.COMEM_CHRGE_ADDR2 IS '담당자 주소 상세(도로명)';

COMMENT ON COLUMN T_COMEMBER.COMEM_CHRGE_CELL IS '담당자휴대폰';

COMMENT ON COLUMN T_COMEMBER.COMEM_CHRGE_TEL IS '담당자회사전화';

COMMENT ON COLUMN T_COMEMBER.COMEM_CHRGE_MAIL IS '담당자이메일';

COMMENT ON COLUMN T_COMEMBER.COMEM_CHRGE_TNAME IS '팀장성명';

COMMENT ON COLUMN T_COMEMBER.COMEM_CHRGE_TMAIL IS '팀장이메일';

COMMENT ON COLUMN T_COMEMBER.COMEM_STATUS IS '기업상태';

COMMENT ON COLUMN T_COMEMBER.ETC1 IS '여분필드1';

COMMENT ON COLUMN T_COMEMBER.ETC2 IS '여분필드2';

COMMENT ON COLUMN T_COMEMBER.USEYN IS '사용여부';

COMMENT ON COLUMN T_COMEMBER.REGDT IS '등록일';

COMMENT ON COLUMN T_COMEMBER.UPDDT IS '수정일';

COMMENT ON COLUMN T_COMEMBER.DELDT IS '삭제일';

COMMENT ON COLUMN T_COMEMBER.REGMEMID IS '등록자아이디';

COMMENT ON COLUMN T_COMEMBER.UPDMEMID IS '수정자아이디';

COMMENT ON COLUMN T_COMEMBER.DELMEMID IS '삭제자아이디';

COMMENT ON COLUMN T_COMEMBER.DELYN IS '삭제';



--
-- T_COMMENT  (Table)
--
CREATE TABLE T_COMMENT
(
  C_IDX        NUMBER(11)                       NOT NULL,
  C_WRITER     VARCHAR2(60 BYTE)                DEFAULT NULL,
  C_CONTENTS   CLOB                             NOT NULL,
  REGMEMID     VARCHAR2(60 BYTE)                NOT NULL,
  REGDT        TIMESTAMP(6)                     DEFAULT SYSDATE               NOT NULL,
  UPDMEMID     VARCHAR2(60 BYTE)                DEFAULT NULL,
  UPDDT        TIMESTAMP(6)                     DEFAULT SYSDATE               NOT NULL,
  DELYN        CHAR(1 BYTE)                     DEFAULT 'N'                   NOT NULL,
  DELMEMID     VARCHAR2(60 BYTE)                DEFAULT NULL,
  DELDT        DATE                             DEFAULT NULL,
  BD_IDX       NUMBER(11)                       NOT NULL,
  C_REIDX      NUMBER(11)                       NOT NULL,
  C_RECOMID    VARCHAR2(60 BYTE)                DEFAULT NULL,
  C_RECOMNAME  VARCHAR2(60 BYTE)                DEFAULT NULL
);

COMMENT ON TABLE T_COMMENT IS '댓글 테이블';

COMMENT ON COLUMN T_COMMENT.C_IDX IS '댓글 인덱스';

COMMENT ON COLUMN T_COMMENT.C_WRITER IS '댓글 작성자';

COMMENT ON COLUMN T_COMMENT.C_CONTENTS IS '댓글 내용';

COMMENT ON COLUMN T_COMMENT.REGMEMID IS '작성자 아이디';

COMMENT ON COLUMN T_COMMENT.REGDT IS '작성일';

COMMENT ON COLUMN T_COMMENT.UPDMEMID IS '수정자 아이디';

COMMENT ON COLUMN T_COMMENT.UPDDT IS '수정일';

COMMENT ON COLUMN T_COMMENT.DELYN IS '삭제여부';

COMMENT ON COLUMN T_COMMENT.DELMEMID IS '삭제자 아이디';

COMMENT ON COLUMN T_COMMENT.DELDT IS '삭제일';

COMMENT ON COLUMN T_COMMENT.BD_IDX IS '게시글 번호';

COMMENT ON COLUMN T_COMMENT.C_REIDX IS '대댓글 인덱스';

COMMENT ON COLUMN T_COMMENT.C_RECOMID IS '대댓글 아이디';

COMMENT ON COLUMN T_COMMENT.C_RECOMNAME IS '대댓글 이름';



--
-- T_CONNECTION_LOG  (Table)
--
CREATE TABLE T_CONNECTION_LOG
(
  CL_IDX       NUMBER(20)                       NOT NULL,
  CL_AGENT     VARCHAR2(1500 BYTE)              DEFAULT NULL,
  CL_OS        VARCHAR2(450 BYTE)               DEFAULT NULL,
  CL_BROWSER   VARCHAR2(450 BYTE)               DEFAULT NULL,
  CL_KEYWORD   VARCHAR2(300 BYTE)               DEFAULT NULL,
  CL_REFERER   VARCHAR2(1500 BYTE)              DEFAULT NULL,
  CL_IP        VARCHAR2(150 BYTE)               DEFAULT NULL,
  CL_LANGUAGE  VARCHAR2(150 BYTE)               DEFAULT NULL,
  REGDT        TIMESTAMP(6)                     DEFAULT SYSDATE               NOT NULL
);

COMMENT ON TABLE T_CONNECTION_LOG IS '접속로그데터이터';

COMMENT ON COLUMN T_CONNECTION_LOG.CL_IDX IS '접속인덱스';

COMMENT ON COLUMN T_CONNECTION_LOG.CL_AGENT IS '접속정보';

COMMENT ON COLUMN T_CONNECTION_LOG.CL_OS IS '운영체제';

COMMENT ON COLUMN T_CONNECTION_LOG.CL_BROWSER IS '브라우저';

COMMENT ON COLUMN T_CONNECTION_LOG.CL_KEYWORD IS '검색어';

COMMENT ON COLUMN T_CONNECTION_LOG.CL_REFERER IS '유입경로';

COMMENT ON COLUMN T_CONNECTION_LOG.CL_IP IS '접속아이피';

COMMENT ON COLUMN T_CONNECTION_LOG.CL_LANGUAGE IS '접속언어';

COMMENT ON COLUMN T_CONNECTION_LOG.REGDT IS '접속일';



--
-- T_CONTRACT  (Table)
--
CREATE TABLE T_CONTRACT
(
  NO        NUMBER(11),
  TITLE     VARCHAR2(135 BYTE)                  NOT NULL,
  CONTENTS  CLOB                                NOT NULL,
  REQUIRED  NUMBER(4)                           DEFAULT '1'                   NOT NULL,
  REGMEMID  VARCHAR2(60 BYTE)                   DEFAULT NULL,
  UPDMEMID  VARCHAR2(60 BYTE)                   DEFAULT NULL,
  DELMEMID  VARCHAR2(60 BYTE)                   DEFAULT NULL,
  REGDT     TIMESTAMP(6)                        DEFAULT SYSDATE               NOT NULL,
  UPDDT     TIMESTAMP(6)                        DEFAULT SYSDATE               NOT NULL,
  DELDT     DATE                                DEFAULT NULL,
  DELYN     CHAR(1 BYTE)                        DEFAULT 'N'
);

COMMENT ON TABLE T_CONTRACT IS '회원 약관';

COMMENT ON COLUMN T_CONTRACT.NO IS '인덱스';

COMMENT ON COLUMN T_CONTRACT.TITLE IS '약관 제목';

COMMENT ON COLUMN T_CONTRACT.CONTENTS IS '약관 내용';

COMMENT ON COLUMN T_CONTRACT.REQUIRED IS '필수/선택 여부';

COMMENT ON COLUMN T_CONTRACT.REGMEMID IS '등록 관리자 ID';

COMMENT ON COLUMN T_CONTRACT.UPDMEMID IS '수정 관리자 ID';

COMMENT ON COLUMN T_CONTRACT.DELMEMID IS '삭제 관리자 ID';

COMMENT ON COLUMN T_CONTRACT.REGDT IS '등록일';

COMMENT ON COLUMN T_CONTRACT.UPDDT IS '수정일';

COMMENT ON COLUMN T_CONTRACT.DELDT IS '삭제일';

COMMENT ON COLUMN T_CONTRACT.DELYN IS '삭제 여부';



--
-- T_COUNT_DATE  (Table)
--
CREATE TABLE T_COUNT_DATE
(
  CD_IDX      NUMBER(20)                        NOT NULL,
  CNT_OPTION  VARCHAR2(50 BYTE)                 NOT NULL,
  CNT_YEAR    CHAR(4 BYTE)                      DEFAULT '2000'                NOT NULL,
  CNT_MONTH   CHAR(2 BYTE)                      DEFAULT '00'                  NOT NULL,
  CNT_DAY     CHAR(2 BYTE)                      DEFAULT '00'                  NOT NULL,
  CNT_HOUR    CHAR(2 BYTE)                      DEFAULT '00'                  NOT NULL,
  CNT_COUNT   NUMBER(20)                        DEFAULT '1'                   NOT NULL,
  SITE_CODE   VARCHAR2(60 BYTE)                 DEFAULT ''                    NOT NULL,
  ETC         VARCHAR2(300 BYTE)                DEFAULT NULL
);

COMMENT ON TABLE T_COUNT_DATE IS '날짜별 접속통계정보';

COMMENT ON COLUMN T_COUNT_DATE.CD_IDX IS '인덱스';

COMMENT ON COLUMN T_COUNT_DATE.CNT_OPTION IS '구분';

COMMENT ON COLUMN T_COUNT_DATE.CNT_YEAR IS '년도';

COMMENT ON COLUMN T_COUNT_DATE.CNT_MONTH IS '월';

COMMENT ON COLUMN T_COUNT_DATE.CNT_DAY IS '일';

COMMENT ON COLUMN T_COUNT_DATE.CNT_HOUR IS '24시';

COMMENT ON COLUMN T_COUNT_DATE.CNT_COUNT IS '카운트';

COMMENT ON COLUMN T_COUNT_DATE.SITE_CODE IS '사이트코드';

COMMENT ON COLUMN T_COUNT_DATE.ETC IS '기타';



--
-- T_COUNT_MENU  (Table)
--
CREATE TABLE T_COUNT_MENU
(
  CM_IDX      NUMBER(20)                        NOT NULL,
  CNT_OPTION  VARCHAR2(150 BYTE)                NOT NULL,
  CNT_NAME    VARCHAR2(150 BYTE)                NOT NULL,
  CNT_YEAR    CHAR(4 BYTE)                      DEFAULT '2000'                NOT NULL,
  CNT_MONTH   CHAR(2 BYTE)                      DEFAULT '00'                  NOT NULL,
  CNT_DAY     CHAR(2 BYTE)                      DEFAULT '00'                  NOT NULL,
  CNT_COUNT   NUMBER(20)                        DEFAULT '1'                   NOT NULL,
  SITE_CODE   VARCHAR2(60 BYTE)                 DEFAULT ''                    NOT NULL,
  ETC         VARCHAR2(300 BYTE)                DEFAULT NULL
);

COMMENT ON TABLE T_COUNT_MENU IS '메뉴별 접속통계정보';

COMMENT ON COLUMN T_COUNT_MENU.CM_IDX IS '인덱스';

COMMENT ON COLUMN T_COUNT_MENU.CNT_OPTION IS '구분';

COMMENT ON COLUMN T_COUNT_MENU.CNT_NAME IS '메뉴이름';

COMMENT ON COLUMN T_COUNT_MENU.CNT_YEAR IS '년도';

COMMENT ON COLUMN T_COUNT_MENU.CNT_MONTH IS '월';

COMMENT ON COLUMN T_COUNT_MENU.CNT_DAY IS '일';

COMMENT ON COLUMN T_COUNT_MENU.CNT_COUNT IS '카운트';

COMMENT ON COLUMN T_COUNT_MENU.SITE_CODE IS '사이트코드';

COMMENT ON COLUMN T_COUNT_MENU.ETC IS '기타';



--
-- T_COUNT_OPTION  (Table)
--
CREATE TABLE T_COUNT_OPTION
(
  CO_IDX      NUMBER(20)                        NOT NULL,
  CNT_OPTION  VARCHAR2(150 BYTE)                NOT NULL,
  CNT_NAME    VARCHAR2(150 BYTE)                NOT NULL,
  CNT_YEAR    CHAR(4 BYTE)                      DEFAULT '2000'                NOT NULL,
  CNT_MONTH   CHAR(2 BYTE)                      DEFAULT '00'                  NOT NULL,
  CNT_DAY     CHAR(2 BYTE)                      DEFAULT '00'                  NOT NULL,
  CNT_COUNT   NUMBER(20)                        DEFAULT '1'                   NOT NULL,
  SITE_CODE   VARCHAR2(60 BYTE)                 DEFAULT ''                    NOT NULL,
  ETC         VARCHAR2(300 BYTE)                DEFAULT NULL
);

COMMENT ON TABLE T_COUNT_OPTION IS '조건별 접속통계정보';

COMMENT ON COLUMN T_COUNT_OPTION.CO_IDX IS '인덱스';

COMMENT ON COLUMN T_COUNT_OPTION.CNT_OPTION IS '구분';

COMMENT ON COLUMN T_COUNT_OPTION.CNT_NAME IS '이름';

COMMENT ON COLUMN T_COUNT_OPTION.CNT_YEAR IS '년도';

COMMENT ON COLUMN T_COUNT_OPTION.CNT_MONTH IS '월';

COMMENT ON COLUMN T_COUNT_OPTION.CNT_DAY IS '일';

COMMENT ON COLUMN T_COUNT_OPTION.CNT_COUNT IS '카운트';

COMMENT ON COLUMN T_COUNT_OPTION.SITE_CODE IS '사이트코드';

COMMENT ON COLUMN T_COUNT_OPTION.ETC IS '기타';



--
-- T_COUNT_POPUP  (Table)
--
CREATE TABLE T_COUNT_POPUP
(
  CP_IDX      NUMBER(20)                        NOT NULL,
  POP_IDX     NUMBER(20)                        NOT NULL,
  CNT_OPTION  VARCHAR2(150 BYTE)                NOT NULL,
  CNT_YEAR    CHAR(4 BYTE)                      DEFAULT '0000'                NOT NULL,
  CNT_MONTH   CHAR(2 BYTE)                      DEFAULT '00'                  NOT NULL,
  CNT_DAY     CHAR(2 BYTE)                      DEFAULT '00'                  NOT NULL,
  CNT_COUNT   NUMBER(20)                        DEFAULT '1'                   NOT NULL,
  SITE_CODE   VARCHAR2(60 BYTE)                 DEFAULT ''                    NOT NULL,
  ETC         VARCHAR2(300 BYTE)
);

COMMENT ON TABLE T_COUNT_POPUP IS '팝업 통계정보';

COMMENT ON COLUMN T_COUNT_POPUP.CP_IDX IS '인덱스';

COMMENT ON COLUMN T_COUNT_POPUP.POP_IDX IS '팝업 인덱스';

COMMENT ON COLUMN T_COUNT_POPUP.CNT_OPTION IS '구분';

COMMENT ON COLUMN T_COUNT_POPUP.CNT_YEAR IS '년도';

COMMENT ON COLUMN T_COUNT_POPUP.CNT_MONTH IS '월';

COMMENT ON COLUMN T_COUNT_POPUP.CNT_DAY IS '일';

COMMENT ON COLUMN T_COUNT_POPUP.CNT_COUNT IS '카운트';

COMMENT ON COLUMN T_COUNT_POPUP.SITE_CODE IS '사이트코드';

COMMENT ON COLUMN T_COUNT_POPUP.ETC IS '기타';



--
-- T_COUNT_SNS  (Table)
--
CREATE TABLE T_COUNT_SNS
(
  CS_IDX       NUMBER(20)                       NOT NULL,
  CNT_NAME     VARCHAR2(150 BYTE)               NOT NULL,
  CNT_URL      VARCHAR2(600 BYTE)               NOT NULL,
  CNT_SM_NAME  VARCHAR2(60 BYTE)                NOT NULL,
  CNT_OPTION   VARCHAR2(150 BYTE)               NOT NULL,
  CNT_YEAR     CHAR(4 BYTE)                     DEFAULT '0000'                NOT NULL,
  CNT_MONTH    CHAR(2 BYTE)                     DEFAULT '00'                  NOT NULL,
  CNT_DAY      CHAR(2 BYTE)                     DEFAULT '00'                  NOT NULL,
  CNT_COUNT    NUMBER(20)                       DEFAULT '1'                   NOT NULL,
  SITE_CODE    VARCHAR2(60 BYTE)                DEFAULT ''                    NOT NULL,
  ETC          VARCHAR2(300 BYTE)
);

COMMENT ON TABLE T_COUNT_SNS IS 'SNS 공유 통계정보';

COMMENT ON COLUMN T_COUNT_SNS.CS_IDX IS '인덱스';

COMMENT ON COLUMN T_COUNT_SNS.CNT_NAME IS '메뉴이름';

COMMENT ON COLUMN T_COUNT_SNS.CNT_URL IS 'URL';

COMMENT ON COLUMN T_COUNT_SNS.CNT_SM_NAME IS 'SNS이름';

COMMENT ON COLUMN T_COUNT_SNS.CNT_OPTION IS '구분';

COMMENT ON COLUMN T_COUNT_SNS.CNT_YEAR IS '년도';

COMMENT ON COLUMN T_COUNT_SNS.CNT_MONTH IS '월';

COMMENT ON COLUMN T_COUNT_SNS.CNT_DAY IS '일';

COMMENT ON COLUMN T_COUNT_SNS.CNT_COUNT IS '카운트';

COMMENT ON COLUMN T_COUNT_SNS.SITE_CODE IS '사이트코드';

COMMENT ON COLUMN T_COUNT_SNS.ETC IS '기타';


--
-- T_IPCOUNTRY  (Table)
--
CREATE TABLE T_IPCOUNTRY
(
  STARTIPNUM    VARCHAR2(33 BYTE)               DEFAULT NULL,
  ENDIPNUM      VARCHAR2(33 BYTE)               DEFAULT NULL,
  COUNTRYCODE2  VARCHAR2(150 BYTE)              DEFAULT NULL,
  COUNTRYCODE3  VARCHAR2(150 BYTE)              DEFAULT NULL,
  COUNTRYNAME   VARCHAR2(183 BYTE)              DEFAULT NULL
);

--
-- T_IPMANAGE  (Table)
--
CREATE TABLE T_IPMANAGE
(
  NO            NUMBER(11)                      NOT NULL,
  SITE_CODE     VARCHAR2(45 BYTE)               NOT NULL,
  IP_DESC_TYPE  NUMBER(1)                       DEFAULT NULL,
  IP_DESC       CLOB,
  REGMEMID      VARCHAR2(135 BYTE)              DEFAULT NULL,
  UPDMEMID      VARCHAR2(135 BYTE)              DEFAULT NULL,
  REGDT         TIMESTAMP(6)                    DEFAULT SYSDATE               NOT NULL,
  UPDDT         TIMESTAMP(6)                    DEFAULT SYSDATE               NOT NULL
);

COMMENT ON COLUMN T_IPMANAGE.REGMEMID IS '등록자아이디';

COMMENT ON COLUMN T_IPMANAGE.UPDMEMID IS '수정자아이디';

COMMENT ON COLUMN T_IPMANAGE.REGDT IS '등록일';

COMMENT ON COLUMN T_IPMANAGE.UPDDT IS '수정일';



--
-- T_JOINFORM  (Table)
--
CREATE TABLE T_JOINFORM
(
  NO            NUMBER(11)                      NOT NULL,
  NAME          NUMBER(1)                       DEFAULT '0',
  NICKNAME      NUMBER(1)                       DEFAULT '0',
  PASSTRYCNT    NUMBER(11)                      DEFAULT '0',
  PHONE         NUMBER(1)                       DEFAULT '0',
  MOBILE        NUMBER(1)                       DEFAULT '0',
  EMAIL         NUMBER(1)                       DEFAULT '0',
  FAX           NUMBER(1)                       DEFAULT '0',
  ADDRESS       NUMBER(1)                       DEFAULT '0',
  BIRTH         NUMBER(1)                       DEFAULT '0',
  SEX           NUMBER(1)                       DEFAULT '0',
  GRP           NUMBER(1)                       DEFAULT '0',
  REGMEMID      VARCHAR2(60 BYTE)               DEFAULT NULL,
  UPDMEMID      VARCHAR2(60 BYTE)               DEFAULT NULL,
  REGDT         TIMESTAMP(6)                    DEFAULT SYSDATE               NOT NULL,
  UPDDT         TIMESTAMP(6)                    DEFAULT SYSDATE               NOT NULL,
  CONTRACTDESC  VARCHAR2(150 BYTE)              DEFAULT '',
  SITECODE      VARCHAR2(60 BYTE)               DEFAULT '',
  USE_JOINWAIT  NUMBER(1)                       DEFAULT '0'
);

COMMENT ON TABLE T_JOINFORM IS '회원 가입 폼 설정 테이블(0사용하지 않음,1:사용함(필수), 2:사용함(선택))';

COMMENT ON COLUMN T_JOINFORM.NO IS '인덱스';

COMMENT ON COLUMN T_JOINFORM.NAME IS '이름';

COMMENT ON COLUMN T_JOINFORM.NICKNAME IS '닉네임';

COMMENT ON COLUMN T_JOINFORM.PASSTRYCNT IS '비밀번호오류횟수';

COMMENT ON COLUMN T_JOINFORM.PHONE IS '전화번호';

COMMENT ON COLUMN T_JOINFORM.MOBILE IS '휴대전화';

COMMENT ON COLUMN T_JOINFORM.EMAIL IS '이메일';

COMMENT ON COLUMN T_JOINFORM.FAX IS '팩스';

COMMENT ON COLUMN T_JOINFORM.ADDRESS IS '주소';

COMMENT ON COLUMN T_JOINFORM.BIRTH IS '생년월일';

COMMENT ON COLUMN T_JOINFORM.SEX IS '성별';

COMMENT ON COLUMN T_JOINFORM.GRP IS '회원그룹';

COMMENT ON COLUMN T_JOINFORM.REGMEMID IS '등록자아이디';

COMMENT ON COLUMN T_JOINFORM.UPDMEMID IS '수정자아이디';

COMMENT ON COLUMN T_JOINFORM.REGDT IS '등록일';

COMMENT ON COLUMN T_JOINFORM.UPDDT IS '수정일';

COMMENT ON COLUMN T_JOINFORM.CONTRACTDESC IS '약관 descriptor';

COMMENT ON COLUMN T_JOINFORM.SITECODE IS '사이트코드';

COMMENT ON COLUMN T_JOINFORM.USE_JOINWAIT IS '가입승인';



--
-- T_LOGIN_LOG  (Table)
--
CREATE TABLE T_LOGIN_LOG
(
  LOG_REGDT    TIMESTAMP(6)                     DEFAULT SYSDATE               NOT NULL,
  LOG_ID       VARCHAR2(90 BYTE)                DEFAULT NULL,
  LOG_TYPE     CHAR(1 BYTE)                     DEFAULT NULL,
  LOG_IP       VARCHAR2(192 BYTE)               DEFAULT NULL,
  LOG_AGENT    VARCHAR2(1500 BYTE)              DEFAULT NULL,
  LOG_OS       VARCHAR2(150 BYTE)               DEFAULT NULL,
  LOG_DEVICE   VARCHAR2(150 BYTE)               DEFAULT NULL,
  LOG_BROWSER  VARCHAR2(150 BYTE)               DEFAULT NULL,
  LOG_SITE     VARCHAR2(60 BYTE)                DEFAULT NULL
);

COMMENT ON TABLE T_LOGIN_LOG IS '로그인 로그';

COMMENT ON COLUMN T_LOGIN_LOG.LOG_REGDT IS '접속일시';

COMMENT ON COLUMN T_LOGIN_LOG.LOG_ID IS '아이디';

COMMENT ON COLUMN T_LOGIN_LOG.LOG_TYPE IS '로그인타입(사용자,관리자)';

COMMENT ON COLUMN T_LOGIN_LOG.LOG_IP IS '아이피';

COMMENT ON COLUMN T_LOGIN_LOG.LOG_AGENT IS '브라우저 정보';

COMMENT ON COLUMN T_LOGIN_LOG.LOG_OS IS '운영체제';

COMMENT ON COLUMN T_LOGIN_LOG.LOG_DEVICE IS '디바이스';

COMMENT ON COLUMN T_LOGIN_LOG.LOG_BROWSER IS '브라우저';

COMMENT ON COLUMN T_LOGIN_LOG.LOG_SITE IS '로그인사이트';



--
-- T_MANAGER  (Table)
--
CREATE TABLE T_MANAGER
(
  MNG_ID          VARCHAR2(60 BYTE)             NOT NULL,
  MNG_NAME        VARCHAR2(60 BYTE)             DEFAULT NULL,
  MNG_PASS        VARCHAR2(192 BYTE)            DEFAULT NULL,
  MNG_PHONE       VARCHAR2(192 BYTE)            DEFAULT NULL,
  MNG_MOBILE      VARCHAR2(192 BYTE)            DEFAULT NULL,
  MNG_EMAIL       VARCHAR2(192 BYTE)            DEFAULT NULL,
  MNG_FAX         VARCHAR2(192 BYTE)            DEFAULT NULL,
  MNG_WORK        VARCHAR2(60 BYTE)             DEFAULT NULL,
  GROUP_CODE      VARCHAR2(60 BYTE)             DEFAULT NULL,
  POSITION_CODE   VARCHAR2(60 BYTE)             DEFAULT NULL,
  SITE_CODE_META  VARCHAR2(900 BYTE)            DEFAULT NULL,
  MNG_IPYN        CHAR(1 BYTE)                  DEFAULT NULL,
  MNG_IP          VARCHAR2(900 BYTE)            DEFAULT NULL,
  MNG_PASSDT      DATE                          DEFAULT NULL,
  MNG_PASSTRYCNT  NUMBER(6)                     DEFAULT NULL,
  MNG_TYPE        VARCHAR2(60 BYTE)             DEFAULT NULL,
  MNG_AUTH        CHAR(2 BYTE)                  DEFAULT '00',
  MNG_POWER       VARCHAR2(60 BYTE)             DEFAULT NULL,
  MNG_ROLE        VARCHAR2(60 BYTE)             DEFAULT NULL,
  REGDT           DATE                          DEFAULT SYSDATE               NOT NULL,
  UPDDT           DATE                          DEFAULT SYSDATE               NOT NULL,
  DELDT           DATE                          DEFAULT NULL,
  REGMEMID        VARCHAR2(60 BYTE)             DEFAULT NULL,
  UPDMEMID        VARCHAR2(60 BYTE)             DEFAULT NULL,
  DELMEMID        VARCHAR2(60 BYTE)             DEFAULT NULL,
  DELYN           CHAR(1 BYTE)                  DEFAULT NULL
);

COMMENT ON TABLE T_MANAGER IS '관리자정보';

COMMENT ON COLUMN T_MANAGER.MNG_ID IS '관리자아이디';

COMMENT ON COLUMN T_MANAGER.MNG_NAME IS '이름';

COMMENT ON COLUMN T_MANAGER.MNG_PASS IS '비밀번호';

COMMENT ON COLUMN T_MANAGER.MNG_PHONE IS '전화번호';

COMMENT ON COLUMN T_MANAGER.MNG_MOBILE IS '휴대폰번호';

COMMENT ON COLUMN T_MANAGER.MNG_EMAIL IS '이메일주소';

COMMENT ON COLUMN T_MANAGER.MNG_FAX IS '팩스번호';

COMMENT ON COLUMN T_MANAGER.MNG_WORK IS '담당업무';

COMMENT ON COLUMN T_MANAGER.GROUP_CODE IS '부서코드';

COMMENT ON COLUMN T_MANAGER.POSITION_CODE IS '직위';

COMMENT ON COLUMN T_MANAGER.SITE_CODE_META IS '사이트코드';

COMMENT ON COLUMN T_MANAGER.MNG_IPYN IS '아이피제한사용여부';

COMMENT ON COLUMN T_MANAGER.MNG_IP IS '아이피';

COMMENT ON COLUMN T_MANAGER.MNG_PASSDT IS '비밀번호수정일';

COMMENT ON COLUMN T_MANAGER.MNG_PASSTRYCNT IS '비밀번호오류횟수';

COMMENT ON COLUMN T_MANAGER.MNG_TYPE IS '관리자구분';

COMMENT ON COLUMN T_MANAGER.MNG_AUTH IS '관리자등급';

COMMENT ON COLUMN T_MANAGER.MNG_POWER IS '관리자권한인덱스';

COMMENT ON COLUMN T_MANAGER.MNG_ROLE IS '컨텐츠권한인덱스';

COMMENT ON COLUMN T_MANAGER.REGDT IS '등록일';

COMMENT ON COLUMN T_MANAGER.UPDDT IS '수정일';

COMMENT ON COLUMN T_MANAGER.DELDT IS '삭제일';

COMMENT ON COLUMN T_MANAGER.REGMEMID IS '등록자아이디';

COMMENT ON COLUMN T_MANAGER.UPDMEMID IS '수정자아이디';

COMMENT ON COLUMN T_MANAGER.DELMEMID IS '삭제자아이디';

COMMENT ON COLUMN T_MANAGER.DELYN IS '삭제여부';



--
-- T_MANAGER_LOG  (Table)
--
CREATE TABLE T_MANAGER_LOG
(
  MLOG_REGDT         TIMESTAMP(6)               DEFAULT SYSDATE               NOT NULL,
  MLOG_CLASS         VARCHAR2(765 BYTE)         DEFAULT NULL,
  MLOG_METHOD        VARCHAR2(765 BYTE)         DEFAULT NULL,
  MLOG_TYPE          CHAR(1 BYTE)               DEFAULT NULL,
  MNG_ID             VARCHAR2(90 BYTE)          DEFAULT NULL,
  MNG_NAME           VARCHAR2(90 BYTE)          DEFAULT NULL,
  MLOG_IP            VARCHAR2(192 BYTE)         DEFAULT NULL,
  MLOG_URL           VARCHAR2(3000 BYTE)        DEFAULT NULL,
  MLOG_REFERER       VARCHAR2(3000 BYTE)        DEFAULT NULL,
  MLOG_PERSONALINFO  CHAR(3 BYTE)               DEFAULT '0'
);

COMMENT ON TABLE T_MANAGER_LOG IS '관리자 작업 로그';

COMMENT ON COLUMN T_MANAGER_LOG.MLOG_REGDT IS '저장일시';

COMMENT ON COLUMN T_MANAGER_LOG.MLOG_CLASS IS '클래스명';

COMMENT ON COLUMN T_MANAGER_LOG.MLOG_METHOD IS '메쏘드명';

COMMENT ON COLUMN T_MANAGER_LOG.MLOG_TYPE IS '작업구분';

COMMENT ON COLUMN T_MANAGER_LOG.MNG_ID IS '관리자아이디';

COMMENT ON COLUMN T_MANAGER_LOG.MNG_NAME IS '관리자이름';

COMMENT ON COLUMN T_MANAGER_LOG.MLOG_IP IS '접속아이피';

COMMENT ON COLUMN T_MANAGER_LOG.MLOG_URL IS '접속주소';

COMMENT ON COLUMN T_MANAGER_LOG.MLOG_REFERER IS 'referer';

COMMENT ON COLUMN T_MANAGER_LOG.MLOG_PERSONALINFO IS '개인정보접근권한변경';



--
-- T_MANAGER_MENU_AUTH  (Table)
--
CREATE TABLE T_MANAGER_MENU_AUTH
(
  MANAGER_MENU_AUTH_IDX  NUMBER(22)             NOT NULL,
  MENU_AUTH_IDX          NUMBER(22)             NOT NULL,
  MNG_ID                 VARCHAR2(60 BYTE)      NOT NULL,
  REGDT                  DATE                   DEFAULT SYSDATE,
  UPDDT                  DATE                   DEFAULT SYSDATE,
  DELDT                  DATE                   DEFAULT NULL,
  REGMEMID               VARCHAR2(60 BYTE)      DEFAULT NULL,
  UPDMEMID               VARCHAR2(60 BYTE)      DEFAULT NULL,
  DELMEMID               VARCHAR2(60 BYTE)      DEFAULT NULL,
  DELYN                  CHAR(1 BYTE)           DEFAULT 'N'
);

COMMENT ON TABLE T_MANAGER_MENU_AUTH IS '관리자-메뉴권한 매칭';

COMMENT ON COLUMN T_MANAGER_MENU_AUTH.MANAGER_MENU_AUTH_IDX IS '관리자-메뉴권한 매칭 인덱스';

COMMENT ON COLUMN T_MANAGER_MENU_AUTH.MENU_AUTH_IDX IS '메뉴권한인덱스';

COMMENT ON COLUMN T_MANAGER_MENU_AUTH.MNG_ID IS '관리자아이디';

COMMENT ON COLUMN T_MANAGER_MENU_AUTH.REGDT IS '등록일';

COMMENT ON COLUMN T_MANAGER_MENU_AUTH.UPDDT IS '수정일';

COMMENT ON COLUMN T_MANAGER_MENU_AUTH.DELDT IS '삭제일';

COMMENT ON COLUMN T_MANAGER_MENU_AUTH.REGMEMID IS '등록자아이디';

COMMENT ON COLUMN T_MANAGER_MENU_AUTH.UPDMEMID IS '수정자아이디';

COMMENT ON COLUMN T_MANAGER_MENU_AUTH.DELMEMID IS '삭제자아이디';

COMMENT ON COLUMN T_MANAGER_MENU_AUTH.DELYN IS '삭제';



--
-- T_MANAGER_SITE  (Table)
--
CREATE TABLE T_MANAGER_SITE
(
  MANAGER_SITE_IDX  NUMBER(22)                  NOT NULL,
  SITE_CODE         VARCHAR2(60 BYTE)           NOT NULL,
  MNG_ID            VARCHAR2(60 BYTE)           NOT NULL,
  REGDT             DATE                        DEFAULT SYSDATE,
  UPDDT             DATE                        DEFAULT SYSDATE,
  DELDT             DATE                        DEFAULT NULL,
  REGMEMID          VARCHAR2(60 BYTE)           DEFAULT NULL,
  UPDMEMID          VARCHAR2(60 BYTE)           DEFAULT NULL,
  DELMEMID          VARCHAR2(60 BYTE)           DEFAULT NULL,
  DELYN             CHAR(1 BYTE)                DEFAULT 'N'
);

COMMENT ON TABLE T_MANAGER_SITE IS '관리자-관리사이트 매칭';

COMMENT ON COLUMN T_MANAGER_SITE.MANAGER_SITE_IDX IS '관리자-관리사이트 매칭 인덱스';

COMMENT ON COLUMN T_MANAGER_SITE.SITE_CODE IS '관리사이트코드';

COMMENT ON COLUMN T_MANAGER_SITE.MNG_ID IS '관리자아이디';

COMMENT ON COLUMN T_MANAGER_SITE.REGDT IS '등록일';

COMMENT ON COLUMN T_MANAGER_SITE.UPDDT IS '수정일';

COMMENT ON COLUMN T_MANAGER_SITE.DELDT IS '삭제일';

COMMENT ON COLUMN T_MANAGER_SITE.REGMEMID IS '등록자아이디';

COMMENT ON COLUMN T_MANAGER_SITE.UPDMEMID IS '수정자아이디';

COMMENT ON COLUMN T_MANAGER_SITE.DELMEMID IS '삭제자아이디';

COMMENT ON COLUMN T_MANAGER_SITE.DELYN IS '삭제';



--
-- T_MEMBER  (Table)
--
CREATE TABLE T_MEMBER
(
  ID                VARCHAR2(60 BYTE)           NOT NULL,
  NAME              VARCHAR2(60 BYTE)           DEFAULT NULL,
  NICKNAME          VARCHAR2(60 BYTE)           DEFAULT NULL,
  PASS              VARCHAR2(192 BYTE)          DEFAULT NULL,
  PASSDT            DATE                        DEFAULT NULL,
  PASSTRYCNT        NUMBER(11)                  DEFAULT '0',
  PHONE             VARCHAR2(192 BYTE)          DEFAULT NULL,
  MOBILE            VARCHAR2(192 BYTE)          DEFAULT NULL,
  EMAIL             VARCHAR2(192 BYTE)          DEFAULT NULL,
  FAX               VARCHAR2(192 BYTE)          DEFAULT NULL,
  OLDPOST           VARCHAR2(30 BYTE)           DEFAULT NULL,
  OLDADDR1          VARCHAR2(600 BYTE)          DEFAULT NULL,
  OLDADDR2          VARCHAR2(600 BYTE)          DEFAULT NULL,
  NEWPOST           VARCHAR2(18 BYTE)           DEFAULT NULL,
  NEWADDR1          VARCHAR2(600 BYTE)          DEFAULT NULL,
  NEWADDR2          VARCHAR2(600 BYTE)          DEFAULT NULL,
  BIRTH             VARCHAR2(30 BYTE)           DEFAULT NULL,
  SEX               CHAR(1 BYTE)                DEFAULT 'M',
  TYPE              VARCHAR2(60 BYTE)           DEFAULT NULL,
  "GROUP"           CHAR(2 BYTE)                DEFAULT '00',
  CODE              CHAR(2 BYTE)                DEFAULT '00',
  COMEM_IDX         NUMBER(20)                  DEFAULT NULL,
  POSITION          VARCHAR2(60 BYTE)           DEFAULT NULL,
  LOGINIP           VARCHAR2(60 BYTE)           DEFAULT NULL,
  LOGINDT           TIMESTAMP(6)                DEFAULT SYSDATE               NOT NULL,
  LOGINCOUNTRYCD    CHAR(6 BYTE)                DEFAULT NULL,
  LOGINCOUNTRYNAME  VARCHAR2(300 BYTE)          DEFAULT NULL,
  LOGINBROWSER      VARCHAR2(300 BYTE)          DEFAULT NULL,
  LOGINBROWSERICON  VARCHAR2(300 BYTE)          DEFAULT NULL,
  LOGINOS           VARCHAR2(300 BYTE)          DEFAULT NULL,
  LOGINOSICON       VARCHAR2(300 BYTE)          DEFAULT NULL,
  REGID             VARCHAR2(60 BYTE)           DEFAULT NULL,
  REGIP             VARCHAR2(60 BYTE)           DEFAULT NULL,
  REGDT             TIMESTAMP(6)                DEFAULT SYSDATE               NOT NULL,
  REGCOUNTRYCD      CHAR(6 BYTE)                DEFAULT NULL,
  REGCOUNTRYNAME    VARCHAR2(300 BYTE)          DEFAULT NULL,
  REGBROWSER        VARCHAR2(300 BYTE)          DEFAULT NULL,
  REGBROWSERICON    VARCHAR2(300 BYTE)          DEFAULT NULL,
  REGOS             VARCHAR2(300 BYTE)          DEFAULT NULL,
  REGOSICON         VARCHAR2(300 BYTE)          DEFAULT NULL,
  UPDID             VARCHAR2(60 BYTE)           DEFAULT NULL,
  UPDIP             VARCHAR2(60 BYTE)           DEFAULT NULL,
  UPDDT             TIMESTAMP(6)                DEFAULT SYSDATE               NOT NULL,
  STATUS            VARCHAR2(60 BYTE)           DEFAULT NULL,
  DELID             VARCHAR2(60 BYTE)           DEFAULT NULL,
  DELIP             VARCHAR2(60 BYTE)           DEFAULT NULL,
  DELDT             DATE                        DEFAULT NULL,
  CUTOFFDT          DATE                        DEFAULT NULL,
  CUTOFFREASON      CLOB,
  SMSYN             CHAR(1 BYTE)                DEFAULT 'Y',
  EMAILYN           CHAR(1 BYTE)                DEFAULT 'Y',
  INFOOPENYN        CHAR(1 BYTE)                DEFAULT 'Y',
  REGSITECODE       VARCHAR2(60 BYTE)           DEFAULT '',
  UNIONMEM          NUMBER(4)                   DEFAULT '1',
  ETC1              VARCHAR2(135 BYTE)          DEFAULT NULL,
  DELYN             CHAR(1 BYTE)
);

COMMENT ON TABLE T_MEMBER IS '멤버 관리';

COMMENT ON COLUMN T_MEMBER.ID IS '회원아이디';

COMMENT ON COLUMN T_MEMBER.NAME IS '이름';

COMMENT ON COLUMN T_MEMBER.NICKNAME IS '닉네임';

COMMENT ON COLUMN T_MEMBER.PASS IS '비밀번호';

COMMENT ON COLUMN T_MEMBER.PASSDT IS '비밀번호수정일';

COMMENT ON COLUMN T_MEMBER.PASSTRYCNT IS '비밀번호오류횟수';

COMMENT ON COLUMN T_MEMBER.PHONE IS '전화번호';

COMMENT ON COLUMN T_MEMBER.MOBILE IS '휴대전화';

COMMENT ON COLUMN T_MEMBER.EMAIL IS '이메일';

COMMENT ON COLUMN T_MEMBER.FAX IS '팩스';

COMMENT ON COLUMN T_MEMBER.OLDPOST IS '구 우편번호';

COMMENT ON COLUMN T_MEMBER.OLDADDR1 IS '구 주소';

COMMENT ON COLUMN T_MEMBER.OLDADDR2 IS '구 주소 상세';

COMMENT ON COLUMN T_MEMBER.NEWPOST IS '신 우편주소(도로명)';

COMMENT ON COLUMN T_MEMBER.NEWADDR1 IS '신 주소(도로명)';

COMMENT ON COLUMN T_MEMBER.NEWADDR2 IS '신 주소 상세(도로명)';

COMMENT ON COLUMN T_MEMBER.BIRTH IS '생년월일';

COMMENT ON COLUMN T_MEMBER.SEX IS '성별';

COMMENT ON COLUMN T_MEMBER.TYPE IS '회원타입';

COMMENT ON COLUMN T_MEMBER."GROUP" IS '회원그룹';

COMMENT ON COLUMN T_MEMBER.CODE IS '회원코드';

COMMENT ON COLUMN T_MEMBER.COMEM_IDX IS '기업회원 인덱스(연계시 사용)';

COMMENT ON COLUMN T_MEMBER.POSITION IS '직급';

COMMENT ON COLUMN T_MEMBER.LOGINIP IS '로그인아이피';

COMMENT ON COLUMN T_MEMBER.LOGINDT IS '로그인일자';

COMMENT ON COLUMN T_MEMBER.LOGINCOUNTRYCD IS '접속국가코드';

COMMENT ON COLUMN T_MEMBER.LOGINCOUNTRYNAME IS '접속국가명';

COMMENT ON COLUMN T_MEMBER.LOGINBROWSER IS '접속브라우져';

COMMENT ON COLUMN T_MEMBER.LOGINBROWSERICON IS '로그인브라우져아이콘';

COMMENT ON COLUMN T_MEMBER.LOGINOS IS '접속 OS';

COMMENT ON COLUMN T_MEMBER.LOGINOSICON IS '로그인os아이콘';

COMMENT ON COLUMN T_MEMBER.REGID IS '가입자아이디';

COMMENT ON COLUMN T_MEMBER.REGIP IS '가입아이피';

COMMENT ON COLUMN T_MEMBER.REGDT IS '가입일자';

COMMENT ON COLUMN T_MEMBER.REGCOUNTRYCD IS '가입국가코드';

COMMENT ON COLUMN T_MEMBER.REGCOUNTRYNAME IS '가입국가명';

COMMENT ON COLUMN T_MEMBER.REGBROWSER IS '가입 브라우져';

COMMENT ON COLUMN T_MEMBER.REGBROWSERICON IS '가입브라우저아이콘';

COMMENT ON COLUMN T_MEMBER.REGOS IS '가입 OS';

COMMENT ON COLUMN T_MEMBER.REGOSICON IS '등록 OS 아이콘';

COMMENT ON COLUMN T_MEMBER.UPDID IS '수정자아이디';

COMMENT ON COLUMN T_MEMBER.UPDIP IS '수정자아이피';

COMMENT ON COLUMN T_MEMBER.UPDDT IS '수정일';

COMMENT ON COLUMN T_MEMBER.STATUS IS '회원상태: 0:정상, 1:차단,2:삭제(탈퇴)';

COMMENT ON COLUMN T_MEMBER.DELID IS '삭제자아이디';

COMMENT ON COLUMN T_MEMBER.DELIP IS '삭제자아이피';

COMMENT ON COLUMN T_MEMBER.DELDT IS '삭제일';

COMMENT ON COLUMN T_MEMBER.CUTOFFDT IS '차단일자';

COMMENT ON COLUMN T_MEMBER.CUTOFFREASON IS '차단사유';

COMMENT ON COLUMN T_MEMBER.SMSYN IS '문자수신여부';

COMMENT ON COLUMN T_MEMBER.EMAILYN IS '이메일수신여부';

COMMENT ON COLUMN T_MEMBER.INFOOPENYN IS '정보공개허용여부';

COMMENT ON COLUMN T_MEMBER.REGSITECODE IS '가입한 사이트코드';

COMMENT ON COLUMN T_MEMBER.UNIONMEM IS '통합회원 사용 여부';

COMMENT ON COLUMN T_MEMBER.ETC1 IS '여분필드';

COMMENT ON COLUMN T_MEMBER.DELYN IS '삭제여부';



--
-- T_MENU  (Table)
--
CREATE TABLE T_MENU
(
  MENU_IDX            NUMBER(22)                DEFAULT 0                     NOT NULL,
  MENU_PCODE          VARCHAR2(50 BYTE)         DEFAULT NULL,
  MENU_CODE           VARCHAR2(50 BYTE)         NOT NULL,
  MENU_NAME           VARCHAR2(150 BYTE)        DEFAULT NULL,
  MENU_TYPE           CHAR(1 BYTE)              DEFAULT '5',
  MENU_SUBTYPE        VARCHAR2(300 BYTE)        DEFAULT NULL,
  MENU_CATEGORY       VARCHAR2(300 BYTE)        DEFAULT NULL,
  MENU_URL            VARCHAR2(300 BYTE)        DEFAULT NULL,
  MENU_MNGURL         VARCHAR2(300 BYTE)        DEFAULT NULL,
  MENU_SITECODE       VARCHAR2(60 BYTE)         DEFAULT NULL,
  MENU_DEPTH          NUMBER(22)                DEFAULT NULL,
  MENU_ORDER          NUMBER(22)                DEFAULT NULL,
  MENU_FULLORDER      VARCHAR2(30 BYTE)         DEFAULT NULL,
  MENU_PFULLCODE      VARCHAR2(1000 BYTE)       DEFAULT NULL,
  MENU_PFULLNAME      VARCHAR2(1000 BYTE)       DEFAULT NULL,
  MENU_NAVI           VARCHAR2(1000 BYTE)       DEFAULT NULL,
  MENU_MEMO           VARCHAR2(1000 BYTE)       DEFAULT NULL,
  MENU_CONTENTS       NUMBER(22)                DEFAULT NULL,
  MENU_MAINPAGE       NUMBER(22)                DEFAULT 0,
  MENU_SHOWTYPE       CHAR(1 BYTE)              DEFAULT '0',
  MENU_USETYPE        CHAR(1 BYTE)              DEFAULT '0',
  MENU_USEFIXWIDTH    CHAR(1 BYTE)              DEFAULT '0',
  MENU_CHARGEUSEYN    CHAR(1 BYTE)              DEFAULT 'N',
  MENU_RESEARCHUSEYN  CHAR(1 BYTE)              DEFAULT 'N',
  MENU_LNBUSEYN       CHAR(1 BYTE)              DEFAULT 'Y',
  MENU_QRUSEYN        CHAR(1 BYTE)              DEFAULT 'N',
  MENU_SNSSHAREYN     CHAR(1 BYTE)              DEFAULT 'N',
  MENU_USEYN          CHAR(1 BYTE)              DEFAULT 'Y',
  MNG_ID              VARCHAR2(60 BYTE)         DEFAULT NULL,
  REGDT               DATE                      DEFAULT SYSDATE,
  UPDDT               DATE                      DEFAULT SYSDATE,
  DELDT               DATE                      DEFAULT NULL,
  REGMEMID            VARCHAR2(60 BYTE)         DEFAULT NULL,
  UPDMEMID            VARCHAR2(60 BYTE)         DEFAULT NULL,
  DELMEMID            VARCHAR2(60 BYTE)         DEFAULT NULL,
  DELYN               CHAR(1 BYTE)              DEFAULT 'N'
);

COMMENT ON TABLE T_MENU IS '메뉴관리';

COMMENT ON COLUMN T_MENU.MENU_IDX IS '메뉴인덱스';

COMMENT ON COLUMN T_MENU.MENU_PCODE IS '부모메뉴코드';

COMMENT ON COLUMN T_MENU.MENU_CODE IS '메뉴코드';

COMMENT ON COLUMN T_MENU.MENU_NAME IS '메뉴이름';

COMMENT ON COLUMN T_MENU.MENU_TYPE IS '메뉴타입';

COMMENT ON COLUMN T_MENU.MENU_SUBTYPE IS '메뉴하위타입';

COMMENT ON COLUMN T_MENU.MENU_CATEGORY IS '메뉴카테고리';

COMMENT ON COLUMN T_MENU.MENU_URL IS '링크주소';

COMMENT ON COLUMN T_MENU.MENU_MNGURL IS '관리자주소';

COMMENT ON COLUMN T_MENU.MENU_SITECODE IS '메뉴가속한사이트';

COMMENT ON COLUMN T_MENU.MENU_DEPTH IS '뎁스';

COMMENT ON COLUMN T_MENU.MENU_ORDER IS '순서';

COMMENT ON COLUMN T_MENU.MENU_FULLORDER IS '계층유지순서';

COMMENT ON COLUMN T_MENU.MENU_PFULLCODE IS '메뉴전체코드';

COMMENT ON COLUMN T_MENU.MENU_PFULLNAME IS '메뉴전체이름';

COMMENT ON COLUMN T_MENU.MENU_NAVI IS '네비게이션';

COMMENT ON COLUMN T_MENU.MENU_MEMO IS '메모';

COMMENT ON COLUMN T_MENU.MENU_CONTENTS IS '메뉴컨텐츠인덱스';

COMMENT ON COLUMN T_MENU.MENU_MAINPAGE IS '메인페이지노출';

COMMENT ON COLUMN T_MENU.MENU_SHOWTYPE IS '메뉴방식';

COMMENT ON COLUMN T_MENU.MENU_USETYPE IS '메뉴사용구분';

COMMENT ON COLUMN T_MENU.MENU_USEFIXWIDTH IS '페이지형태';

COMMENT ON COLUMN T_MENU.MENU_CHARGEUSEYN IS '담당자사용여부';

COMMENT ON COLUMN T_MENU.MENU_RESEARCHUSEYN IS '만족도사용여부';

COMMENT ON COLUMN T_MENU.MENU_LNBUSEYN IS '사이드메뉴사용여부';

COMMENT ON COLUMN T_MENU.MENU_QRUSEYN IS 'QR사용여부';

COMMENT ON COLUMN T_MENU.MENU_SNSSHAREYN IS 'SNS공유사용여부';

COMMENT ON COLUMN T_MENU.MENU_USEYN IS '사용여부';

COMMENT ON COLUMN T_MENU.MNG_ID IS '담당자아이디';

COMMENT ON COLUMN T_MENU.REGDT IS '등록일';

COMMENT ON COLUMN T_MENU.UPDDT IS '수정일';

COMMENT ON COLUMN T_MENU.DELDT IS '삭제일';

COMMENT ON COLUMN T_MENU.REGMEMID IS '등록자아이디';

COMMENT ON COLUMN T_MENU.UPDMEMID IS '수정자아이디';

COMMENT ON COLUMN T_MENU.DELMEMID IS '삭제자아이디';

COMMENT ON COLUMN T_MENU.DELYN IS '삭제여부';



--
-- T_MENU_AUTH  (Table)
--
CREATE TABLE T_MENU_AUTH
(
  MENU_AUTH_IDX        NUMBER(22)               NOT NULL,
  MENU_AUTH_NAME       VARCHAR2(150 BYTE)       DEFAULT NULL,
  MENU_AUTH_SITECODE   VARCHAR2(60 BYTE)        DEFAULT NULL,
  REGDT                DATE                     DEFAULT SYSDATE,
  UPDDT                DATE                     DEFAULT SYSDATE,
  DELDT                DATE                     DEFAULT NULL,
  REGMEMID             VARCHAR2(60 BYTE)        DEFAULT NULL,
  UPDMEMID             VARCHAR2(60 BYTE)        DEFAULT NULL,
  DELMEMID             VARCHAR2(60 BYTE)        DEFAULT NULL,
  DELYN                CHAR(1 BYTE)             DEFAULT 'N',
  MENU_AUTH_ITEM_META  VARCHAR2(1000 BYTE)      DEFAULT NULL,
  MENU_AUTH_TYPE       CHAR(1 BYTE)             DEFAULT '1'                   NOT NULL
);

COMMENT ON TABLE T_MENU_AUTH IS '메뉴권한관리';

COMMENT ON COLUMN T_MENU_AUTH.MENU_AUTH_IDX IS '메뉴권한인덱스';

COMMENT ON COLUMN T_MENU_AUTH.MENU_AUTH_NAME IS '메뉴권한이름';

COMMENT ON COLUMN T_MENU_AUTH.MENU_AUTH_SITECODE IS '메뉴권한사이트';

COMMENT ON COLUMN T_MENU_AUTH.REGDT IS '등록일';

COMMENT ON COLUMN T_MENU_AUTH.UPDDT IS '수정일';

COMMENT ON COLUMN T_MENU_AUTH.DELDT IS '삭제일';

COMMENT ON COLUMN T_MENU_AUTH.REGMEMID IS '등록자아이디';

COMMENT ON COLUMN T_MENU_AUTH.UPDMEMID IS '수정자아이디';

COMMENT ON COLUMN T_MENU_AUTH.DELMEMID IS '삭제자아이디';

COMMENT ON COLUMN T_MENU_AUTH.DELYN IS '삭제';

COMMENT ON COLUMN T_MENU_AUTH.MENU_AUTH_ITEM_META IS '메뉴권한아이템메타';

COMMENT ON COLUMN T_MENU_AUTH.MENU_AUTH_TYPE IS '메뉴권한타입';



--
-- T_MENU_AUTH_ITEM  (Table)
--
CREATE TABLE T_MENU_AUTH_ITEM
(
  ITEM_IDX       NUMBER(22)                     NOT NULL,
  MENU_AUTH_IDX  NUMBER(22)                     DEFAULT NULL,
  MENU_CODE      VARCHAR2(60 BYTE)              DEFAULT NULL,
  AUTH_C         CHAR(1 BYTE)                   DEFAULT 'N',
  AUTH_R         CHAR(1 BYTE)                   DEFAULT 'N',
  AUTH_U         CHAR(1 BYTE)                   DEFAULT 'N',
  AUTH_D         CHAR(1 BYTE)                   DEFAULT 'N',
  REGDT          DATE                           DEFAULT SYSDATE,
  UPDDT          DATE                           DEFAULT SYSDATE,
  DELDT          DATE                           DEFAULT NULL,
  REGMEMID       VARCHAR2(60 BYTE)              DEFAULT NULL,
  UPDMEMID       VARCHAR2(60 BYTE)              DEFAULT NULL,
  DELMEMID       VARCHAR2(60 BYTE)              DEFAULT NULL,
  DELYN          CHAR(1 BYTE)                   DEFAULT 'N'
);

COMMENT ON TABLE T_MENU_AUTH_ITEM IS '메뉴권한별접근메뉴';

COMMENT ON COLUMN T_MENU_AUTH_ITEM.ITEM_IDX IS '메뉴권한별접근메뉴인덱스';

COMMENT ON COLUMN T_MENU_AUTH_ITEM.MENU_AUTH_IDX IS '메뉴권한인덱스';

COMMENT ON COLUMN T_MENU_AUTH_ITEM.MENU_CODE IS '메뉴코드';

COMMENT ON COLUMN T_MENU_AUTH_ITEM.AUTH_C IS '쓰기권한';

COMMENT ON COLUMN T_MENU_AUTH_ITEM.AUTH_R IS '읽기권한';

COMMENT ON COLUMN T_MENU_AUTH_ITEM.AUTH_U IS '수정권한';

COMMENT ON COLUMN T_MENU_AUTH_ITEM.AUTH_D IS '삭제권한';

COMMENT ON COLUMN T_MENU_AUTH_ITEM.REGDT IS '등록일';

COMMENT ON COLUMN T_MENU_AUTH_ITEM.UPDDT IS '수정일';

COMMENT ON COLUMN T_MENU_AUTH_ITEM.DELDT IS '삭제일';

COMMENT ON COLUMN T_MENU_AUTH_ITEM.REGMEMID IS '등록자아이디';

COMMENT ON COLUMN T_MENU_AUTH_ITEM.UPDMEMID IS '수정자아이디';

COMMENT ON COLUMN T_MENU_AUTH_ITEM.DELMEMID IS '삭제자아이디';

COMMENT ON COLUMN T_MENU_AUTH_ITEM.DELYN IS '삭제여부';



--
-- T_MENU_CONTENTS  (Table)
--
CREATE TABLE T_MENU_CONTENTS
(
  MC_IDX        NUMBER(20)                      NOT NULL,
  MENU_CODE     VARCHAR2(60 BYTE)               DEFAULT NULL,
  MC_CONTENT    CLOB,
  MC_MEMO       CLOB,
  MC_PREVIEWYN  CHAR(1 BYTE)                    DEFAULT NULL,
  REGDT         TIMESTAMP(6)                    DEFAULT SYSDATE               NOT NULL,
  UPDDT         TIMESTAMP(6)                    DEFAULT SYSDATE               NOT NULL,
  DELDT         DATE                            DEFAULT NULL,
  REGMEMID      VARCHAR2(60 BYTE)               DEFAULT NULL,
  UPDMEMID      VARCHAR2(60 BYTE)               DEFAULT NULL,
  DELMEMID      VARCHAR2(60 BYTE)               DEFAULT NULL,
  DELYN         CHAR(1 BYTE)                    DEFAULT NULL
);

COMMENT ON TABLE T_MENU_CONTENTS IS '컨텐츠관리';

COMMENT ON COLUMN T_MENU_CONTENTS.MC_IDX IS '컨텐츠관리 인덱스';

COMMENT ON COLUMN T_MENU_CONTENTS.MENU_CODE IS '메뉴코드';

COMMENT ON COLUMN T_MENU_CONTENTS.MC_CONTENT IS '내용';

COMMENT ON COLUMN T_MENU_CONTENTS.MC_MEMO IS '메모';

COMMENT ON COLUMN T_MENU_CONTENTS.MC_PREVIEWYN IS '미리보기사용여부';

COMMENT ON COLUMN T_MENU_CONTENTS.REGDT IS '등록일';

COMMENT ON COLUMN T_MENU_CONTENTS.UPDDT IS '수정일';

COMMENT ON COLUMN T_MENU_CONTENTS.DELDT IS '삭제일';

COMMENT ON COLUMN T_MENU_CONTENTS.REGMEMID IS '등록자';

COMMENT ON COLUMN T_MENU_CONTENTS.UPDMEMID IS '수정자';

COMMENT ON COLUMN T_MENU_CONTENTS.DELMEMID IS '삭제자';

COMMENT ON COLUMN T_MENU_CONTENTS.DELYN IS '삭제여부';



--
-- T_MENU_PROGRAM  (Table)
--
CREATE TABLE T_MENU_PROGRAM
(
  MENU_CODE  VARCHAR2(60 BYTE)                  NOT NULL,
  PROG_IDX   NUMBER(20)                         NOT NULL,
  MP_OPT1    VARCHAR2(60 BYTE)                  DEFAULT NULL,
  MP_OPT2    VARCHAR2(60 BYTE)                  DEFAULT NULL,
  MP_OPT3    VARCHAR2(60 BYTE)                  DEFAULT NULL,
  MP_VALUE1  VARCHAR2(600 BYTE)                 DEFAULT NULL,
  MP_VALUE2  VARCHAR2(600 BYTE)                 DEFAULT NULL,
  MP_VALUE3  VARCHAR2(600 BYTE)                 DEFAULT NULL,
  REGDT      TIMESTAMP(6)                       DEFAULT SYSDATE               NOT NULL
);

COMMENT ON TABLE T_MENU_PROGRAM IS '메뉴 프로그램 상세';

COMMENT ON COLUMN T_MENU_PROGRAM.MENU_CODE IS '메뉴코드';

COMMENT ON COLUMN T_MENU_PROGRAM.PROG_IDX IS '프로그램관리인덱스';

COMMENT ON COLUMN T_MENU_PROGRAM.MP_OPT1 IS '옵션1';

COMMENT ON COLUMN T_MENU_PROGRAM.MP_OPT2 IS '옵션2';

COMMENT ON COLUMN T_MENU_PROGRAM.MP_OPT3 IS '옵션3';

COMMENT ON COLUMN T_MENU_PROGRAM.MP_VALUE1 IS '값1';

COMMENT ON COLUMN T_MENU_PROGRAM.MP_VALUE2 IS '값2';

COMMENT ON COLUMN T_MENU_PROGRAM.MP_VALUE3 IS '값3';

COMMENT ON COLUMN T_MENU_PROGRAM.REGDT IS '등록일';



--
-- T_MENU_SATISFACTION  (Table)
--
CREATE TABLE T_MENU_SATISFACTION
(
  MENU_CODE  VARCHAR2(60 BYTE)                  DEFAULT NULL,
  ID         VARCHAR2(60 BYTE)                  DEFAULT NULL,
  TYPE       CHAR(3 BYTE)                       DEFAULT NULL,
  ANSWER1    VARCHAR2(60 BYTE)                  DEFAULT NULL,
  ANSWER2    VARCHAR2(60 BYTE)                  DEFAULT NULL,
  ANSWER3    VARCHAR2(60 BYTE)                  DEFAULT NULL,
  ANSWER4    VARCHAR2(60 BYTE)                  DEFAULT NULL,
  ANSWER5    VARCHAR2(60 BYTE)                  DEFAULT NULL,
  ANSWER6    VARCHAR2(1500 BYTE)                DEFAULT NULL,
  REGDT      TIMESTAMP(6)                       DEFAULT SYSDATE               NOT NULL,
  IP         VARCHAR2(192 BYTE)                 DEFAULT NULL
);

COMMENT ON TABLE T_MENU_SATISFACTION IS '메뉴 만족도';

COMMENT ON COLUMN T_MENU_SATISFACTION.MENU_CODE IS '메뉴코드';

COMMENT ON COLUMN T_MENU_SATISFACTION.ID IS '아이디';

COMMENT ON COLUMN T_MENU_SATISFACTION.TYPE IS '구분';

COMMENT ON COLUMN T_MENU_SATISFACTION.ANSWER1 IS '응답1';

COMMENT ON COLUMN T_MENU_SATISFACTION.ANSWER2 IS '응답2';

COMMENT ON COLUMN T_MENU_SATISFACTION.ANSWER3 IS '응답3';

COMMENT ON COLUMN T_MENU_SATISFACTION.ANSWER4 IS '응답4';

COMMENT ON COLUMN T_MENU_SATISFACTION.ANSWER5 IS '응답5';

COMMENT ON COLUMN T_MENU_SATISFACTION.ANSWER6 IS '응답6';

COMMENT ON COLUMN T_MENU_SATISFACTION.REGDT IS '등록일';

COMMENT ON COLUMN T_MENU_SATISFACTION.IP IS '아이피';



--
-- T_ORGAN_CHART  (Table)
--
CREATE TABLE T_ORGAN_CHART
(
  OR_IDX      NUMBER(20)                        NOT NULL,
  TOP_CODE    VARCHAR2(60 BYTE)                 NOT NULL,
  COLUMN_CNT  NUMBER(1)                         NOT NULL,
  COLUMN_NM1  VARCHAR2(50 BYTE),
  COLUMN_NM2  VARCHAR2(50 BYTE),
  COLUMN_NM3  VARCHAR2(50 BYTE)
);

COMMENT ON TABLE T_ORGAN_CHART IS '조직도관리';

COMMENT ON COLUMN T_ORGAN_CHART.OR_IDX IS '조직도설정인덱스';

COMMENT ON COLUMN T_ORGAN_CHART.TOP_CODE IS '최상위부서코드';

COMMENT ON COLUMN T_ORGAN_CHART.COLUMN_CNT IS '부서단위(열)수';

COMMENT ON COLUMN T_ORGAN_CHART.COLUMN_NM1 IS '부서단위명1';

COMMENT ON COLUMN T_ORGAN_CHART.COLUMN_NM2 IS '부서단위명2';

COMMENT ON COLUMN T_ORGAN_CHART.COLUMN_NM3 IS '부서단위명3';


--
-- T_PERSON_INFO_INQUIRY_LOG  (Table)
--
CREATE TABLE T_PERSON_INFO_INQUIRY_LOG
(
  INQIRE_INDX  NUMBER(20)                       NOT NULL,
  INQIRE_DATE  DATE                             NOT NULL,
  MBER_ID      VARCHAR2(60 BYTE)                NOT NULL,
  REASON       VARCHAR2(3000 BYTE),
  INQIRE_ID    VARCHAR2(60 BYTE),
  INQIRE_NM    VARCHAR2(60 BYTE),
  INQIRE_IP    VARCHAR2(192 BYTE),
  REG_ID       VARCHAR2(60 BYTE),
  UPDT_ID      VARCHAR2(60 BYTE),
  DELETE_ID    VARCHAR2(60 BYTE),
  REG_DATE     DATE,
  UPDT_DATE    DATE,
  DELETE_DATE  DATE,
  DELETE_YN    CHAR(1 BYTE)                     DEFAULT 'N'
);

COMMENT ON TABLE T_PERSON_INFO_INQUIRY_LOG IS '개인정보 조회 로그';

COMMENT ON COLUMN T_PERSON_INFO_INQUIRY_LOG.INQIRE_INDX IS '조회인덱스';

COMMENT ON COLUMN T_PERSON_INFO_INQUIRY_LOG.INQIRE_DATE IS '조회일시';

COMMENT ON COLUMN T_PERSON_INFO_INQUIRY_LOG.MBER_ID IS '회원아이디';

COMMENT ON COLUMN T_PERSON_INFO_INQUIRY_LOG.REASON IS '조회사유';

COMMENT ON COLUMN T_PERSON_INFO_INQUIRY_LOG.INQIRE_ID IS '조회자아이디';

COMMENT ON COLUMN T_PERSON_INFO_INQUIRY_LOG.INQIRE_NM IS '조회자이름';

COMMENT ON COLUMN T_PERSON_INFO_INQUIRY_LOG.INQIRE_IP IS '조회아이피';

COMMENT ON COLUMN T_PERSON_INFO_INQUIRY_LOG.REG_ID IS '등록자';

COMMENT ON COLUMN T_PERSON_INFO_INQUIRY_LOG.UPDT_ID IS '수정자';

COMMENT ON COLUMN T_PERSON_INFO_INQUIRY_LOG.DELETE_ID IS '삭제자';

COMMENT ON COLUMN T_PERSON_INFO_INQUIRY_LOG.REG_DATE IS '조회일시';

COMMENT ON COLUMN T_PERSON_INFO_INQUIRY_LOG.UPDT_DATE IS '수정일시';

COMMENT ON COLUMN T_PERSON_INFO_INQUIRY_LOG.DELETE_DATE IS '삭제일시';

COMMENT ON COLUMN T_PERSON_INFO_INQUIRY_LOG.DELETE_YN IS '삭제여부';

--
-- T_POPUP  (Table)
--
CREATE TABLE T_POPUP
(
  POPUP_IDX       NUMBER(20)                    NOT NULL,
  POPUP_TYPE      CHAR(1 BYTE)                  DEFAULT NULL,
  POPUP_TITLE     VARCHAR2(300 BYTE)            DEFAULT NULL,
  POPUP_USEYN     CHAR(1 BYTE)                  DEFAULT NULL,
  POPUP_MOBILE    CHAR(1 BYTE)                  DEFAULT 'N',
  POPUP_SDT       DATE                          DEFAULT NULL,
  POPUP_STM       VARCHAR2(30 BYTE)             DEFAULT NULL,
  POPUP_EDT       DATE                          DEFAULT NULL,
  POPUP_ETM       VARCHAR2(30 BYTE)             DEFAULT NULL,
  POPUP_IMG       VARCHAR2(300 BYTE)            DEFAULT NULL,
  POPUP_ALT       CLOB,
  POPUP_URL       VARCHAR2(450 BYTE)            DEFAULT NULL,
  POPUP_LINKTYPE  CHAR(1 BYTE)                  DEFAULT NULL,
  POPUP_WIDTH     NUMBER(6)                     DEFAULT NULL,
  POPUP_HEIGHT    NUMBER(6)                     DEFAULT NULL,
  POPUP_ORDER     NUMBER(6)                     DEFAULT NULL,
  REGDT           TIMESTAMP(6)                  DEFAULT SYSDATE               NOT NULL,
  UPDDT           TIMESTAMP(6)                  DEFAULT SYSDATE               NOT NULL,
  DELDT           DATE                          DEFAULT NULL,
  REGMEMID        VARCHAR2(60 BYTE)             DEFAULT NULL,
  UPDMEMID        VARCHAR2(60 BYTE)             DEFAULT NULL,
  DELMEMID        VARCHAR2(60 BYTE)             DEFAULT NULL,
  DELYN           CHAR(1 BYTE)                  DEFAULT NULL,
  EXPIRES         VARCHAR2(3 BYTE),
  POPUP_FILE      VARCHAR2(100 BYTE),
  OLD_FILE_NM     VARCHAR2(100 BYTE),
  MV_FILE         VARCHAR2(100 BYTE),
  OLD_MV_FILE     VARCHAR2(100 BYTE),
  UPLOAD_TYPE     VARCHAR2(10 BYTE),
  STREAM_URL      VARCHAR2(100 BYTE),
  EDIT_CONTENTS   CLOB
);

COMMENT ON TABLE T_POPUP IS '팝업관리';

COMMENT ON COLUMN T_POPUP.POPUP_IDX IS '팝업인덱스';

COMMENT ON COLUMN T_POPUP.POPUP_TYPE IS '팝업구분';

COMMENT ON COLUMN T_POPUP.POPUP_TITLE IS '제목';

COMMENT ON COLUMN T_POPUP.POPUP_USEYN IS '사용여부';

COMMENT ON COLUMN T_POPUP.POPUP_MOBILE IS '모바일 표출 여부';

COMMENT ON COLUMN T_POPUP.POPUP_SDT IS '시작일';

COMMENT ON COLUMN T_POPUP.POPUP_STM IS '시작시';

COMMENT ON COLUMN T_POPUP.POPUP_EDT IS '종료일';

COMMENT ON COLUMN T_POPUP.POPUP_ETM IS '종료시';

COMMENT ON COLUMN T_POPUP.POPUP_IMG IS '이미지';

COMMENT ON COLUMN T_POPUP.POPUP_ALT IS '대체텍스트';

COMMENT ON COLUMN T_POPUP.POPUP_URL IS '주소';

COMMENT ON COLUMN T_POPUP.POPUP_LINKTYPE IS '링크타입';

COMMENT ON COLUMN T_POPUP.POPUP_WIDTH IS '가로사이즈';

COMMENT ON COLUMN T_POPUP.POPUP_HEIGHT IS '세로사이즈';

COMMENT ON COLUMN T_POPUP.POPUP_ORDER IS '순서';

COMMENT ON COLUMN T_POPUP.REGDT IS '등록일';

COMMENT ON COLUMN T_POPUP.UPDDT IS '수정일';

COMMENT ON COLUMN T_POPUP.DELDT IS '삭제일';

COMMENT ON COLUMN T_POPUP.REGMEMID IS '등록자아이디';

COMMENT ON COLUMN T_POPUP.UPDMEMID IS '수정자아이디';

COMMENT ON COLUMN T_POPUP.DELMEMID IS '삭제자아이디';

COMMENT ON COLUMN T_POPUP.DELYN IS '삭제여부';

COMMENT ON COLUMN T_POPUP.EXPIRES IS '닫기설정';

COMMENT ON COLUMN T_POPUP.POPUP_FILE IS '첨부파일';

COMMENT ON COLUMN T_POPUP.OLD_FILE_NM IS '첨부파일명';

COMMENT ON COLUMN T_POPUP.MV_FILE IS '동영상 파일';

COMMENT ON COLUMN T_POPUP.OLD_MV_FILE IS '동영상 파일명';

COMMENT ON COLUMN T_POPUP.UPLOAD_TYPE IS '업로드 형식';

COMMENT ON COLUMN T_POPUP.STREAM_URL IS '실시간 동영상';

COMMENT ON COLUMN T_POPUP.EDIT_CONTENTS IS '에디터 내용';



--
-- T_POPUP_SITE  (Table)
--
CREATE TABLE T_POPUP_SITE
(
  PS_IDX     NUMBER(20)                         NOT NULL,
  POPUP_IDX  NUMBER(20)                         NOT NULL,
  SITE_CODE  VARCHAR2(60 BYTE)                  DEFAULT ''                    NOT NULL
);

COMMENT ON TABLE T_POPUP_SITE IS '팝업사이트';

COMMENT ON COLUMN T_POPUP_SITE.PS_IDX IS '팝업사이트인덱스';

COMMENT ON COLUMN T_POPUP_SITE.POPUP_IDX IS '팝업인덱스';

COMMENT ON COLUMN T_POPUP_SITE.SITE_CODE IS '사이트코드';



--
-- T_PROGRAM  (Table)
--
CREATE TABLE T_PROGRAM
(
  PROG_IDX      NUMBER(20)                      NOT NULL,
  PROG_NAME     VARCHAR2(150 BYTE)              DEFAULT NULL,
  PROG_USERURL  VARCHAR2(300 BYTE)              DEFAULT NULL,
  PROG_MNGRURL  VARCHAR2(300 BYTE)              DEFAULT NULL
);

COMMENT ON TABLE T_PROGRAM IS '프로그램 관리';

COMMENT ON COLUMN T_PROGRAM.PROG_IDX IS '프로그램관리 인덱스';

COMMENT ON COLUMN T_PROGRAM.PROG_NAME IS '프로그램 명';

COMMENT ON COLUMN T_PROGRAM.PROG_USERURL IS '사용자 주소';

COMMENT ON COLUMN T_PROGRAM.PROG_MNGRURL IS '관리자 주소';



--
-- T_SITE  (Table)
--
CREATE TABLE T_SITE
(
  SITE_CODE  VARCHAR2(60 BYTE)                  DEFAULT ''                    NOT NULL,
  SITE_NAME  VARCHAR2(60 BYTE)                  DEFAULT NULL
);

COMMENT ON TABLE T_SITE IS '사이트관리';

COMMENT ON COLUMN T_SITE.SITE_CODE IS '사이트코드';

COMMENT ON COLUMN T_SITE.SITE_NAME IS '사이트이름';



--
-- T_SLIDES  (Table)
--
CREATE TABLE T_SLIDES
(
  SLIDES_IDX        NUMBER(11)                  NOT NULL,
  SLIDES_CODE       VARCHAR2(60 BYTE)           DEFAULT ''                    NOT NULL,
  SLIDES_NAME       VARCHAR2(60 BYTE)           DEFAULT NULL,
  SLIDES_TYPE       VARCHAR2(60 BYTE)           DEFAULT '1',
  SLIDES_ETC1       VARCHAR2(150 BYTE)          DEFAULT NULL,
  SLIDES_ETC2       VARCHAR2(150 BYTE)          DEFAULT NULL,
  USEYN             CHAR(1 BYTE)                DEFAULT 'Y',
  REGDT             TIMESTAMP(6)                DEFAULT SYSDATE               NOT NULL,
  UPDDT             TIMESTAMP(6)                DEFAULT SYSDATE               NOT NULL,
  DELDT             DATE                        DEFAULT NULL,
  REGMEMID          VARCHAR2(60 BYTE)           DEFAULT NULL,
  UPDMEMID          VARCHAR2(60 BYTE)           DEFAULT NULL,
  DELMEMID          VARCHAR2(60 BYTE)           DEFAULT NULL,
  DELYN             CHAR(1 BYTE)                DEFAULT 'N',
  SLIDES_SITE_CODE  VARCHAR2(20 BYTE)
);

COMMENT ON TABLE T_SLIDES IS '슬라이드셋관리';

COMMENT ON COLUMN T_SLIDES.SLIDES_IDX IS '슬라이드셋인덱스';

COMMENT ON COLUMN T_SLIDES.SLIDES_CODE IS '슬라이드셋코드';

COMMENT ON COLUMN T_SLIDES.SLIDES_NAME IS '슬라이드셋이름';

COMMENT ON COLUMN T_SLIDES.SLIDES_TYPE IS '슬라이드셋타입';

COMMENT ON COLUMN T_SLIDES.SLIDES_ETC1 IS '여분필드1';

COMMENT ON COLUMN T_SLIDES.SLIDES_ETC2 IS '여분필드2';

COMMENT ON COLUMN T_SLIDES.USEYN IS '사용여부';

COMMENT ON COLUMN T_SLIDES.REGDT IS '등록일';

COMMENT ON COLUMN T_SLIDES.UPDDT IS '수정일';

COMMENT ON COLUMN T_SLIDES.DELDT IS '삭제일';

COMMENT ON COLUMN T_SLIDES.REGMEMID IS '등록자아이디';

COMMENT ON COLUMN T_SLIDES.UPDMEMID IS '수정자아이디';

COMMENT ON COLUMN T_SLIDES.DELMEMID IS '삭제자아이디';

COMMENT ON COLUMN T_SLIDES.DELYN IS '삭제';

COMMENT ON COLUMN T_SLIDES.SLIDES_SITE_CODE IS '사이트코드';



--
-- T_SLIDE_ITEM  (Table)
--
CREATE TABLE T_SLIDE_ITEM
(
  SLITEM_IDX         NUMBER(20)                 NOT NULL,
  SLIDES_IDX         NUMBER(20)                 DEFAULT NULL,
  SLITEM_TITLE       VARCHAR2(300 BYTE)         DEFAULT NULL,
  SLITEM_IMG         VARCHAR2(300 BYTE)         DEFAULT NULL,
  SLITEM_IMGALT      CLOB,
  SLITEM_LINKGUBUN   CHAR(1 BYTE)               DEFAULT '0',
  SLITEM_LINKTIMG    VARCHAR2(300 BYTE)         DEFAULT NULL,
  SLITEM_LINKTTXT    VARCHAR2(600 BYTE)         DEFAULT NULL,
  SLITEM_LINKTCOLOR  VARCHAR2(150 BYTE)         DEFAULT NULL,
  SLITEM_LINKSIMG    VARCHAR2(300 BYTE)         DEFAULT NULL,
  SLITEM_LINKSTXT    VARCHAR2(600 BYTE)         DEFAULT NULL,
  SLITEM_LINKSCOLOR  VARCHAR2(150 BYTE)         DEFAULT NULL,
  SLITEM_LINKBTN     VARCHAR2(150 BYTE)         DEFAULT NULL,
  SLITEM_LINKURL     VARCHAR2(300 BYTE)         DEFAULT NULL,
  SLITEM_LINKPOSHOR  VARCHAR2(60 BYTE)          DEFAULT 'l',
  SLITEM_LINKPOSVER  VARCHAR2(60 BYTE)          DEFAULT 't',
  SLITEM_LINKTYPE    CHAR(1 BYTE)               DEFAULT '1',
  SLITEM_ORDER       NUMBER(6)                  DEFAULT NULL,
  SLITEM_ETC1        VARCHAR2(150 BYTE)         DEFAULT NULL,
  SLITEM_ETC2        VARCHAR2(150 BYTE)         DEFAULT NULL,
  USEYN              CHAR(1 BYTE)               DEFAULT 'Y',
  REGDT              TIMESTAMP(6)               DEFAULT SYSDATE               NOT NULL,
  UPDDT              TIMESTAMP(6)               DEFAULT SYSDATE               NOT NULL,
  DELDT              DATE                       DEFAULT NULL,
  REGMEMID           VARCHAR2(60 BYTE)          DEFAULT NULL,
  UPDMEMID           VARCHAR2(60 BYTE)          DEFAULT NULL,
  DELMEMID           VARCHAR2(60 BYTE)          DEFAULT NULL,
  DELYN              CHAR(1 BYTE)               DEFAULT 'N'
);

COMMENT ON TABLE T_SLIDE_ITEM IS '슬라이드이미지관리';

COMMENT ON COLUMN T_SLIDE_ITEM.SLITEM_IDX IS '슬라이드인덱스';

COMMENT ON COLUMN T_SLIDE_ITEM.SLIDES_IDX IS '슬라이드셋인덱스';

COMMENT ON COLUMN T_SLIDE_ITEM.SLITEM_TITLE IS '제목';

COMMENT ON COLUMN T_SLIDE_ITEM.SLITEM_IMG IS '이미지';

COMMENT ON COLUMN T_SLIDE_ITEM.SLITEM_IMGALT IS '이미지대체텍스트';

COMMENT ON COLUMN T_SLIDE_ITEM.SLITEM_LINKGUBUN IS '링크사용구분,0.사용안함,1.텍스트,2.이미지';

COMMENT ON COLUMN T_SLIDE_ITEM.SLITEM_LINKTIMG IS '링크아이템 타이틀이미지';

COMMENT ON COLUMN T_SLIDE_ITEM.SLITEM_LINKTTXT IS '링크아이템 타이틀텍스트';

COMMENT ON COLUMN T_SLIDE_ITEM.SLITEM_LINKTCOLOR IS '링크아이템 타이틀색상';

COMMENT ON COLUMN T_SLIDE_ITEM.SLITEM_LINKSIMG IS '링크아이템 설명이미지';

COMMENT ON COLUMN T_SLIDE_ITEM.SLITEM_LINKSTXT IS '링크텍스트 설명텍스트';

COMMENT ON COLUMN T_SLIDE_ITEM.SLITEM_LINKSCOLOR IS '링크아이템 설명색상';

COMMENT ON COLUMN T_SLIDE_ITEM.SLITEM_LINKBTN IS '링크아이템 바로가기버튼';

COMMENT ON COLUMN T_SLIDE_ITEM.SLITEM_LINKURL IS '링크주소';

COMMENT ON COLUMN T_SLIDE_ITEM.SLITEM_LINKPOSHOR IS '링크위치 가로정렬(l,c,r)';

COMMENT ON COLUMN T_SLIDE_ITEM.SLITEM_LINKPOSVER IS '링크위치 세로정렬(t,m,b)';

COMMENT ON COLUMN T_SLIDE_ITEM.SLITEM_LINKTYPE IS '링크타입,1.현재창,2.새창';

COMMENT ON COLUMN T_SLIDE_ITEM.SLITEM_ORDER IS '순서';

COMMENT ON COLUMN T_SLIDE_ITEM.SLITEM_ETC1 IS '여분필드1';

COMMENT ON COLUMN T_SLIDE_ITEM.SLITEM_ETC2 IS '여분필드2';

COMMENT ON COLUMN T_SLIDE_ITEM.USEYN IS '사용여부';

COMMENT ON COLUMN T_SLIDE_ITEM.REGDT IS '등록일';

COMMENT ON COLUMN T_SLIDE_ITEM.UPDDT IS '수정일';

COMMENT ON COLUMN T_SLIDE_ITEM.DELDT IS '삭제일';

COMMENT ON COLUMN T_SLIDE_ITEM.REGMEMID IS '등록자아이디';

COMMENT ON COLUMN T_SLIDE_ITEM.UPDMEMID IS '수정자아이디';

COMMENT ON COLUMN T_SLIDE_ITEM.DELMEMID IS '삭제자아이디';

COMMENT ON COLUMN T_SLIDE_ITEM.DELYN IS '삭제여부';



--
-- T_SMACCESSTOKEN  (Table)
--
CREATE TABLE T_SMACCESSTOKEN
(
  SITE_CODE       VARCHAR2(60 BYTE)             NOT NULL,
  SM_NAME         VARCHAR2(60 BYTE)             NOT NULL,
  SM_ACCESSTOKEN  CLOB,
  SM_ACCESSIBLE   CHAR(1 BYTE)                  DEFAULT 'N'                   NOT NULL,
  SM_USERID       CLOB,
  SM_ISSUEDATE    TIMESTAMP(6)                  DEFAULT NULL,
  SM_ETC2         CLOB
);

--
-- T_SMKEYS  (Table)
--
CREATE TABLE T_SMKEYS
(
  SMKEY_IDX     NUMBER(20)                      DEFAULT 1                     NOT NULL,
  SM_NAME       VARCHAR2(60 BYTE)               NOT NULL,
  SM_APPKEY     VARCHAR2(500 BYTE),
  SM_SECRETKEY  VARCHAR2(500 BYTE),
  USEYN         CHAR(1 BYTE)                    DEFAULT 'Y'                   NOT NULL,
  SM_ETC1       VARCHAR2(500 BYTE),
  SM_ETC2       VARCHAR2(500 BYTE),
  REGMEMID      VARCHAR2(60 BYTE)               NOT NULL,
  UPDMEMID      VARCHAR2(60 BYTE)               DEFAULT NULL,
  DELMEMID      VARCHAR2(60 BYTE)               DEFAULT NULL,
  REGDT         TIMESTAMP(6)                    DEFAULT SYSDATE               NOT NULL,
  UPDDT         TIMESTAMP(6)                    DEFAULT SYSDATE               NOT NULL,
  DELDT         TIMESTAMP(6)                    DEFAULT NULL,
  DELYN         CHAR(1 BYTE)                    DEFAULT 'N',
  ACCOUNT_ID    VARCHAR2(60 BYTE)               DEFAULT NULL,
  EXP1          VARCHAR2(500 BYTE),
  SITE_CODE     VARCHAR2(50 BYTE)
);

COMMENT ON TABLE T_SMKEYS IS '소셜미디어 관련 키 테이블';

COMMENT ON COLUMN T_SMKEYS.SMKEY_IDX IS '소셜미디어키인덱스';

COMMENT ON COLUMN T_SMKEYS.SM_NAME IS '소셜미디어이름';

COMMENT ON COLUMN T_SMKEYS.SM_APPKEY IS '소셜미디어앱키';

COMMENT ON COLUMN T_SMKEYS.SM_SECRETKEY IS '소셜미디어시크릿키';

COMMENT ON COLUMN T_SMKEYS.USEYN IS '사용여부';

COMMENT ON COLUMN T_SMKEYS.SM_ETC1 IS 'etc1';

COMMENT ON COLUMN T_SMKEYS.SM_ETC2 IS 'etc2';

COMMENT ON COLUMN T_SMKEYS.REGMEMID IS '등록자아이디';

COMMENT ON COLUMN T_SMKEYS.UPDMEMID IS '수정자아이디';

COMMENT ON COLUMN T_SMKEYS.DELMEMID IS '삭제자아이디';

COMMENT ON COLUMN T_SMKEYS.REGDT IS '등록일';

COMMENT ON COLUMN T_SMKEYS.UPDDT IS '수정일';

COMMENT ON COLUMN T_SMKEYS.DELDT IS '삭제일';

COMMENT ON COLUMN T_SMKEYS.DELYN IS '삭제여부';

COMMENT ON COLUMN T_SMKEYS.ACCOUNT_ID IS '소셜미디어계정아이디';

COMMENT ON COLUMN T_SMKEYS.EXP1 IS '설명';

COMMENT ON COLUMN T_SMKEYS.SITE_CODE IS '사이트코드';



--
-- T_SMPROGRAM  (Table)
--
CREATE TABLE T_SMPROGRAM
(
  SMPRO_IDX  NUMBER(20)                         NOT NULL,
  MENU_CODE  VARCHAR2(60 BYTE)                  NOT NULL,
  SMKEY_IDX  NUMBER(20)                         NOT NULL,
  USEYN      CHAR(1 BYTE)                       NOT NULL,
  PROM_TEXT  VARCHAR2(120 BYTE)
);

COMMENT ON COLUMN T_SMPROGRAM.SMPRO_IDX IS '소셜미디어프로그램인덱스';

COMMENT ON COLUMN T_SMPROGRAM.MENU_CODE IS '프로그램메뉴코드';

COMMENT ON COLUMN T_SMPROGRAM.SMKEY_IDX IS '소셜미디어키인덱스';

COMMENT ON COLUMN T_SMPROGRAM.USEYN IS '사용여부';

COMMENT ON COLUMN T_SMPROGRAM.PROM_TEXT IS '홍보문구';



--
-- T_SURVEY  (Table)
--
CREATE TABLE T_SURVEY
(
  SV_IDX            NUMBER(11)                  NOT NULL,
  SV_TITLE          CLOB                        NOT NULL,
  SV_OUTLINE        CLOB                        DEFAULT NULL,
  SV_EXPLAIN        CLOB                        DEFAULT NULL,
  SV_STARTDATE      TIMESTAMP(6)                NOT NULL,
  SV_ENDDATE        TIMESTAMP(6)                NOT NULL,
  REGDT             TIMESTAMP(6)                NOT NULL,
  UPDDT             TIMESTAMP(6)                DEFAULT SYSDATE               NOT NULL,
  DELDT             TIMESTAMP(6)                DEFAULT SYSDATE               NOT NULL,
  REGMEMID          VARCHAR2(60 BYTE)           NOT NULL,
  UPDMEMID          VARCHAR2(60 BYTE)           DEFAULT NULL,
  DELMEMID          VARCHAR2(60 BYTE)           DEFAULT NULL,
  USEYN             VARCHAR2(20 BYTE)           DEFAULT 'N'                   NOT NULL,
  DELYN             CHAR(1 BYTE)                DEFAULT 'N'                   NOT NULL,
  ETC1              CLOB                        DEFAULT NULL,
  ETC2              CLOB                        DEFAULT NULL,
  SURVEY_SITE_CODE  VARCHAR2(20 BYTE)
);

COMMENT ON TABLE T_SURVEY IS '설문조사 기본 정보 테이블';

COMMENT ON COLUMN T_SURVEY.SV_IDX IS '설문 인덱스';

COMMENT ON COLUMN T_SURVEY.SV_TITLE IS '설문 제목';

COMMENT ON COLUMN T_SURVEY.SV_OUTLINE IS '설문 개요';

COMMENT ON COLUMN T_SURVEY.SV_EXPLAIN IS '설문 설명';

COMMENT ON COLUMN T_SURVEY.SV_STARTDATE IS '설문 시작일';

COMMENT ON COLUMN T_SURVEY.SV_ENDDATE IS '설문 종료일';

COMMENT ON COLUMN T_SURVEY.REGDT IS '등록일';

COMMENT ON COLUMN T_SURVEY.UPDDT IS '수정일';

COMMENT ON COLUMN T_SURVEY.DELDT IS '삭제일';

COMMENT ON COLUMN T_SURVEY.REGMEMID IS '등록자 아이디';

COMMENT ON COLUMN T_SURVEY.UPDMEMID IS '수정자 아이디';

COMMENT ON COLUMN T_SURVEY.DELMEMID IS '삭제자 아이디';

COMMENT ON COLUMN T_SURVEY.USEYN IS '사용 여부';

COMMENT ON COLUMN T_SURVEY.DELYN IS '삭제 여부';

COMMENT ON COLUMN T_SURVEY.ETC1 IS '여분 컬럼1';

COMMENT ON COLUMN T_SURVEY.ETC2 IS '여분 컬럼2';

COMMENT ON COLUMN T_SURVEY.SURVEY_SITE_CODE IS '설문조사 사이트코드';



--
-- T_SURVEYANSWER  (Table)
--
CREATE TABLE T_SURVEYANSWER
(
  SA_IDX   NUMBER(11)                           NOT NULL,
  SV_IDX   NUMBER(11)                           NOT NULL,
  SA_DATE  TIMESTAMP(6)                         DEFAULT SYSDATE               NOT NULL,
  SA_ID    VARCHAR2(60 BYTE)                    NOT NULL
);

COMMENT ON TABLE T_SURVEYANSWER IS '설문 답변 정보 테이블';

COMMENT ON COLUMN T_SURVEYANSWER.SA_IDX IS '답변 정보 인덱스';

COMMENT ON COLUMN T_SURVEYANSWER.SV_IDX IS '설문 인덱스';

COMMENT ON COLUMN T_SURVEYANSWER.SA_DATE IS '답변 일자';

COMMENT ON COLUMN T_SURVEYANSWER.SA_ID IS '답변자 아이디';



--
-- T_SURVEYOPTION  (Table)
--
CREATE TABLE T_SURVEYOPTION
(
  SO_IDX      NUMBER(11)                        NOT NULL,
  SQ_IDX      NUMBER(11)                        NOT NULL,
  SO_CONTENT  CLOB                              NOT NULL,
  SO_ORDER    NUMBER(11)                        DEFAULT 0                     NOT NULL,
  SO_VALUE    CLOB                              DEFAULT NULL,
  ETC1        CLOB                              DEFAULT NULL,
  ETC2        CLOB                              DEFAULT NULL,
  SO_INPUTYN  CHAR(1 BYTE)                      DEFAULT 'N'
);

COMMENT ON TABLE T_SURVEYOPTION IS '설문조사 선택항목 테이블';

COMMENT ON COLUMN T_SURVEYOPTION.SO_IDX IS '선택항목 인덱스';

COMMENT ON COLUMN T_SURVEYOPTION.SQ_IDX IS '설문 문항 인덱스(참조값)';

COMMENT ON COLUMN T_SURVEYOPTION.SO_CONTENT IS '선택항목 설명';

COMMENT ON COLUMN T_SURVEYOPTION.SO_ORDER IS '선택항목 정렬값';

COMMENT ON COLUMN T_SURVEYOPTION.SO_VALUE IS '선택항목 값';

COMMENT ON COLUMN T_SURVEYOPTION.ETC1 IS 'etc1';

COMMENT ON COLUMN T_SURVEYOPTION.ETC2 IS 'etc2';

COMMENT ON COLUMN T_SURVEYOPTION.SO_INPUTYN IS '설문선택문자열여부';



--
-- T_SURVEYQUESTION  (Table)
--
CREATE TABLE T_SURVEYQUESTION
(
  SQ_IDX         NUMBER(11)                     NOT NULL,
  SV_IDX         NUMBER(11)                     NOT NULL,
  SQ_ANSWERTYPE  VARCHAR2(150 BYTE)             NOT NULL,
  SQ_QUESTION    CLOB                           NOT NULL,
  REGDT          TIMESTAMP(6)                   DEFAULT SYSDATE               NOT NULL,
  UPDDT          TIMESTAMP(6)                   DEFAULT SYSDATE               NOT NULL,
  DELDT          DATE                           DEFAULT NULL,
  REGMEMID       VARCHAR2(60 BYTE)              NOT NULL,
  UPDMEMID       VARCHAR2(60 BYTE)              DEFAULT NULL,
  DELMEMID       VARCHAR2(60 BYTE)              DEFAULT NULL,
  SQ_ORDER       NUMBER(11)                     DEFAULT 0                     NOT NULL,
  DELYN          CHAR(1 BYTE)                   DEFAULT 'N',
  SQ_REQUIRED    CHAR(1 BYTE)                   DEFAULT 'N',
  ETC1           CLOB                           DEFAULT NULL,
  ETC2           CLOB                           DEFAULT NULL,
  SQ_CHECKLIMIT  NUMBER(11)                     DEFAULT NULL,
  SQ_TEXTLIMIT   NUMBER(11)                     DEFAULT 0
);

COMMENT ON TABLE T_SURVEYQUESTION IS '설문조사 문항 테이블';

COMMENT ON COLUMN T_SURVEYQUESTION.SQ_IDX IS '설문조사 문항 인텍스';

COMMENT ON COLUMN T_SURVEYQUESTION.SV_IDX IS '설문조사 인덱스(참조값)';

COMMENT ON COLUMN T_SURVEYQUESTION.SQ_ANSWERTYPE IS '설문조사 문항 답변 타입';

COMMENT ON COLUMN T_SURVEYQUESTION.SQ_QUESTION IS '설문조사 문항 질문';

COMMENT ON COLUMN T_SURVEYQUESTION.REGDT IS '등록일';

COMMENT ON COLUMN T_SURVEYQUESTION.UPDDT IS '수정일';

COMMENT ON COLUMN T_SURVEYQUESTION.DELDT IS '삭제일';

COMMENT ON COLUMN T_SURVEYQUESTION.REGMEMID IS '등록자 아이디';

COMMENT ON COLUMN T_SURVEYQUESTION.UPDMEMID IS '수정자 아이디';

COMMENT ON COLUMN T_SURVEYQUESTION.DELMEMID IS '삭제자 아이디';

COMMENT ON COLUMN T_SURVEYQUESTION.SQ_ORDER IS '문항 순서';

COMMENT ON COLUMN T_SURVEYQUESTION.DELYN IS '삭제 여부';

COMMENT ON COLUMN T_SURVEYQUESTION.SQ_REQUIRED IS '필수값 여부';

COMMENT ON COLUMN T_SURVEYQUESTION.ETC1 IS 'etc1';

COMMENT ON COLUMN T_SURVEYQUESTION.ETC2 IS 'etc2';

COMMENT ON COLUMN T_SURVEYQUESTION.SQ_CHECKLIMIT IS '설문문항 선택제한';

COMMENT ON COLUMN T_SURVEYQUESTION.SQ_TEXTLIMIT IS '설문문항문자열제한';



--
-- T_SURVEYVALUE  (Table)
--
CREATE TABLE T_SURVEYVALUE
(
  SA_IDX    NUMBER(11)                          NOT NULL,
  SQ_IDX    NUMBER(11)                          NOT NULL,
  SO_IDX    NUMBER(11)                          DEFAULT NULL,
  SO_VALUE  CLOB                                NOT NULL
);

COMMENT ON TABLE T_SURVEYVALUE IS '답변 값 테이블';



--
-- T_TEMPLETE  (Table)
--
CREATE TABLE T_TEMPLETE
(
  TEMP_IDX       NUMBER                         NOT NULL,
  TEMP_CODE      VARCHAR2(60 BYTE)              DEFAULT ''                    NOT NULL,
  TEMP_NAME      VARCHAR2(60 BYTE)              DEFAULT NULL,
  RECENT_BD_CNT  VARCHAR2(60 BYTE)              DEFAULT '1'                   NOT NULL,
  TEMP_ETC1      VARCHAR2(150 BYTE)             DEFAULT NULL,
  TEMP_ETC2      VARCHAR2(150 BYTE)             DEFAULT NULL,
  USEYN          CHAR(1 BYTE)                   DEFAULT 'Y',
  REGDT          TIMESTAMP(6)                   DEFAULT SYSDATE               NOT NULL,
  UPDDT          TIMESTAMP(6)                   DEFAULT SYSDATE               NOT NULL,
  DELDT          DATE                           DEFAULT NULL,
  REGMEMID       VARCHAR2(60 BYTE)              DEFAULT NULL,
  UPDMEMID       VARCHAR2(60 BYTE)              DEFAULT NULL,
  DELMEMID       VARCHAR2(60 BYTE)              DEFAULT NULL,
  DELYN          CHAR(1 BYTE)                   DEFAULT 'N',
  SITECODE       VARCHAR2(60 BYTE)
);

COMMENT ON TABLE T_TEMPLETE IS '템플릿설정관리';

COMMENT ON COLUMN T_TEMPLETE.TEMP_IDX IS '템플릿인텍스';

COMMENT ON COLUMN T_TEMPLETE.TEMP_CODE IS '템플릿코드';

COMMENT ON COLUMN T_TEMPLETE.TEMP_NAME IS '템플릿이름';

COMMENT ON COLUMN T_TEMPLETE.RECENT_BD_CNT IS '최신글게시판개수';

COMMENT ON COLUMN T_TEMPLETE.TEMP_ETC1 IS '여분필드1';

COMMENT ON COLUMN T_TEMPLETE.TEMP_ETC2 IS '여분필드2';

COMMENT ON COLUMN T_TEMPLETE.USEYN IS '사용여부';

COMMENT ON COLUMN T_TEMPLETE.REGDT IS '등록일';

COMMENT ON COLUMN T_TEMPLETE.UPDDT IS '수정일';

COMMENT ON COLUMN T_TEMPLETE.DELDT IS '삭제일';

COMMENT ON COLUMN T_TEMPLETE.REGMEMID IS '등록자아이디';

COMMENT ON COLUMN T_TEMPLETE.UPDMEMID IS '수정자아이디';

COMMENT ON COLUMN T_TEMPLETE.DELMEMID IS '삭제자아이디';

COMMENT ON COLUMN T_TEMPLETE.DELYN IS '삭제';

COMMENT ON COLUMN T_TEMPLETE.SITECODE IS '사이트코드';


ALTER TABLE J_ATTACHFILE ADD CONSTRAINT J_ATTACHFILE_PK PRIMARY KEY (FILE_IDX);
ALTER TABLE T_BOARD ADD CONSTRAINT T_BOARD_PK PRIMARY KEY (BD_IDX);
ALTER TABLE T_BOARD_CONFIG ADD CONSTRAINT T_BOARD_CONFIG_PK PRIMARY KEY (BC_ID);
ALTER TABLE T_BOARD_LOB ADD CONSTRAINT T_BOARD_LOB_PK PRIMARY KEY (BL_IDX);
ALTER TABLE T_CODE ADD CONSTRAINT T_CODE_PK PRIMARY KEY (C_CODE);
ALTER TABLE T_COMEMBER ADD CONSTRAINT T_COMEMBER_PK PRIMARY KEY (COMEM_IDX);
ALTER TABLE T_COMMENT ADD CONSTRAINT T_COMMENT_PK PRIMARY KEY (C_IDX);
ALTER TABLE T_CONNECTION_LOG ADD CONSTRAINT T_CONNECTION_LOG_PK PRIMARY KEY (CL_IDX);
ALTER TABLE T_CONTRACT ADD CONSTRAINT T_CONTRACT_PK PRIMARY KEY (NO);
ALTER TABLE T_COUNT_DATE ADD CONSTRAINT T_COUNT_DATE_PK PRIMARY KEY (CD_IDX);
ALTER TABLE T_COUNT_MENU ADD CONSTRAINT T_COUNT_MENU_PK PRIMARY KEY (CM_IDX);
ALTER TABLE T_COUNT_OPTION ADD CONSTRAINT T_COUNT_OPTION_PK PRIMARY KEY (CO_IDX);
ALTER TABLE T_COUNT_POPUP ADD CONSTRAINT T_COUNT_POPUP_PK PRIMARY KEY (CP_IDX);
ALTER TABLE T_COUNT_SNS ADD CONSTRAINT T_COUNT_SNS_PK PRIMARY KEY (CS_IDX);
ALTER TABLE T_IPMANAGE ADD CONSTRAINT T_IPMANAGE_PK PRIMARY KEY (NO);
ALTER TABLE T_JOINFORM ADD CONSTRAINT T_JOINFORM_PK PRIMARY KEY (NO);
ALTER TABLE T_MANAGER ADD CONSTRAINT T_MANAGER_PK PRIMARY KEY (MNG_ID);
ALTER TABLE T_MANAGER_MENU_AUTH ADD CONSTRAINT T_MANAGER_MENU_AUTH_PK PRIMARY KEY (MANAGER_MENU_AUTH_IDX);
ALTER TABLE T_MANAGER_SITE ADD CONSTRAINT T_MANAGER_SITE_PK PRIMARY KEY (MANAGER_SITE_IDX);
ALTER TABLE T_MEMBER ADD CONSTRAINT T_MEMBER_PK PRIMARY KEY (ID);
ALTER TABLE T_MENU ADD CONSTRAINT T_MENU_PK PRIMARY KEY (MENU_IDX);
ALTER TABLE T_MENU_AUTH ADD CONSTRAINT T_MENU_AUTH_PK PRIMARY KEY (MENU_AUTH_IDX);
ALTER TABLE T_MENU_AUTH_ITEM ADD CONSTRAINT T_MENU_AUTH_ITEM_PK PRIMARY KEY (ITEM_IDX);
ALTER TABLE T_MENU_CONTENTS ADD CONSTRAINT T_MENU_CONTENTS_PK PRIMARY KEY (MC_IDX);
ALTER TABLE T_MENU_PROGRAM ADD CONSTRAINT T_MENU_PROGRAM_PK PRIMARY KEY (MENU_CODE, PROG_IDX);
ALTER TABLE T_PERSON_INFO_INQUIRY_LOG ADD CONSTRAINT T_PERSON_INFO_INQUIRY_LOG_PK PRIMARY KEY (INQIRE_INDX);
ALTER TABLE T_POPUP ADD CONSTRAINT T_POPUP_PK PRIMARY KEY (POPUP_IDX);
ALTER TABLE T_POPUP_SITE ADD CONSTRAINT T_POPUP_SITE_PK PRIMARY KEY (PS_IDX);
ALTER TABLE T_PROGRAM ADD CONSTRAINT T_PROGRAM_PK PRIMARY KEY (PROG_IDX);
ALTER TABLE T_SITE ADD CONSTRAINT T_SITE_PK PRIMARY KEY (SITE_CODE);
ALTER TABLE T_SLIDES ADD CONSTRAINT T_SLIDES_PK PRIMARY KEY (SLIDES_IDX);
ALTER TABLE T_SLIDE_ITEM ADD CONSTRAINT T_SLIDE_ITEM_PK PRIMARY KEY (SLITEM_IDX);
ALTER TABLE T_SMACCESSTOKEN ADD CONSTRAINT T_SMACCESSTOKEN_PK PRIMARY KEY (SITE_CODE, SM_NAME);
ALTER TABLE T_SMKEYS ADD CONSTRAINT T_SMKEYS_PK PRIMARY KEY (SMKEY_IDX);
ALTER TABLE T_SMPROGRAM ADD CONSTRAINT T_SMPROGRAM_PK PRIMARY KEY (SMPRO_IDX);
ALTER TABLE T_SURVEY ADD CONSTRAINT T_SURVEY_PK PRIMARY KEY (SV_IDX);
ALTER TABLE T_SURVEYANSWER ADD CONSTRAINT T_SURVEYANSWER_PK PRIMARY KEY (SA_IDX);
ALTER TABLE T_SURVEYOPTION ADD CONSTRAINT T_SURVEYOPTION_PK PRIMARY KEY (SO_IDX);
ALTER TABLE T_SURVEYQUESTION ADD CONSTRAINT T_SURVEYQUESTION_PK PRIMARY KEY (SQ_IDX);
ALTER TABLE T_TEMPLETE ADD CONSTRAINT T_TEMPLETE_PK PRIMARY KEY (TEMP_IDX);

CREATE SEQUENCE J_ATTACHFILE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_BOARD_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_BOARD_CONFIG_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_BOARD_LOB_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_CODE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_COMEMBER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_COMMENT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_CONNECTION_LOG_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_CONTRACT_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_COUNT_DATE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_COUNT_MENU_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_COUNT_OPTION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_COUNT_POPUP_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_COUNT_SNS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_IPMANAGE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_JOINFORM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_MANAGER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_MANAGER_MENU_AUTH_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_MANAGER_SITE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_MEMBER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_MENU_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_MENU_AUTH_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_MENU_AUTH_ITEM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_MENU_CONTENTS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_MENU_PROGRAM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_PERSON_INFO_INQUIRY_LOG_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_POPUP_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_POPUP_SITE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_PROGRAM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_SITE_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_SLIDES_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_SLIDE_ITEM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_SMACCESSTOKEN_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_SMKEYS_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_SMPROGRAM_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_SURVEY_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_SURVEYANSWER_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_SURVEYOPTION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_SURVEYQUESTION_SEQ START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE T_TEMPLETE_SEQ START WITH 1 INCREMENT BY 1;

--
-- T_STAFF  (Table)
--
CREATE TABLE T_STAFF
(
  STAFF_NO     NUMBER(5)                        NOT NULL,
  STAFF_NM     VARCHAR2(50 BYTE)                NOT NULL,
  STAFF_DEPT   VARCHAR2(50 BYTE)                NOT NULL,
  STAFF_POS    VARCHAR2(50 BYTE)                NOT NULL,
  TEL_NO       VARCHAR2(30 BYTE),
  FAX_NO       VARCHAR2(30 BYTE),
  CELL_NO      VARCHAR2(30 BYTE),
  REG_DT       DATE,
  STAFF_WORK   VARCHAR2(4000 BYTE),
  STAFF_EMAIL  VARCHAR2(50 BYTE),
  STAFF_IMG    VARCHAR2(200 BYTE),
  STAFF_HP     VARCHAR2(30 BYTE),
  STAFF_ORD    NUMBER(4),
  OLD_FILE     VARCHAR2(200 BYTE),
  DELYN        VARCHAR2(2 BYTE)
);

COMMENT ON TABLE T_STAFF IS '직원관리';
COMMENT ON COLUMN T_STAFF.STAFF_NO IS '직원인덱스';
COMMENT ON COLUMN T_STAFF.STAFF_NM IS '이름';
COMMENT ON COLUMN T_STAFF.STAFF_DEPT IS '부서';
COMMENT ON COLUMN T_STAFF.STAFF_POS IS '직책';
COMMENT ON COLUMN T_STAFF.TEL_NO IS '전화번호';
COMMENT ON COLUMN T_STAFF.FAX_NO IS 'FAX번호';
COMMENT ON COLUMN T_STAFF.CELL_NO IS '호출번호';
COMMENT ON COLUMN T_STAFF.STAFF_WORK IS '담당업무';
COMMENT ON COLUMN T_STAFF.STAFF_EMAIL IS '이메일';
COMMENT ON COLUMN T_STAFF.OLD_FILE IS '사진원본명';
COMMENT ON COLUMN T_STAFF.REG_DT IS '입사일자';
COMMENT ON COLUMN T_STAFF.STAFF_IMG IS '사진';
COMMENT ON COLUMN T_STAFF.STAFF_HP IS '휴대폰번호';
COMMENT ON COLUMN T_STAFF.STAFF_ORD IS '정렬순서';
COMMENT ON COLUMN T_STAFF.DELYN IS '삭제여부';
