{
    "view_title": "Document Viewer",
    "page_total": "Total ",
    "msg_exception_url_access_failed": "URL access is denied or the page is invalid.",
    "msg_archiveFile_convFail" : "Archive file Conversion failed or is an unsupported archive file format.",
    "help.erro_code.errorcode.2.desc1": "File not supported for conversion.",
    "help.erro_code.errorcode.3.desc1": "Encrypted document not supported.",
    "help.erro_code.errorcode.4.desc1": "DRM document not supported.",
    "help.erro_code.errorcode.22.desc1": "The maximum archive file size you can convert is 500 MB.",
    "help.erro_code.errorcode.101.desc1": "Failed to convert IMAGE.",
    "help.erro_code.errorcode.134.desc1": "Failed to convert IMAGE due to insufficient memory. <br/>Please contact the administrator.",
    "help.erro_code.errorcode.254.desc1": "Expired product license.",
    "help.erro_code.errorcode.255.desc1": "Unknown error",
    "msg_sheet_convFail": "Failed to open sheet.",
    "msg_input_password": "Enter the document's password, please.",
    "msg_exception_open_failed": "Failed to open document. <br>Refresh if you wish to try again.",
    "msg_input_retry": "Wrong password.",
    "msg_refresh": "Refresh",
    "msg_exception_doc": "This document is password protected. <br/> Enter the password to edit the document.",
    "msg_cancel": "Cancel",
    "msg_submit": "OK",
    "msg_download": "Download",
    "msg_light_backgroundcolor": "Light background",
    "msg_dark_backgroundcolor": "Dark background",
    "msg_window_close": "Close window",
    "msg_save_annotation": "Save annotation",
    "msg_fail_save_annotation": "Annotation save failed",
    "msg_delete_marker": "Are you sure you want to delete all markers?",
    "msg_delete_selected_marker": "Are you sure you want to delete the selected marker?",
    "msg_delete_selected_memo": "Are you sure you want to delete the memo?",
    "icon_thumbnail_open": "Open thumbnail",
    "icon_thumbnail_close": "Close thumbnail",
    "icon_thumbnail_drag": "Drag the thumbnail",
    "icon_download": "Download",
    "icon_more": "More",
    "icon_fullscreen_open": "Open Fullscreen",
    "icon_fullscreen_close": "Close Fullscreen",
    "icon_first_sheet": "First sheet",
    "icon_prev_sheet": "Previous sheet",
    "icon_next_sheet": "Next sheet",
    "icon_end_sheet": "Last sheet",
    "icon_prev_page": "Previous page",
    "icon_next_page": "Next page",
    "icon_prev": "Previous",
    "icon_next": "Next",
    "icon_rotate_clockwise": "Rotate to clockwise",
    "icon_zoomin": "Zoom in",
    "icon_zoomout": "Zoom out",
    "icon_originsize": "Original size",
    "icon_pagefit": "Fit to screen",
    "icon_pagewidthfit": "Fit to screen width",
    "icon_move_page_open": "Select page",
    "icon_move_sheet_open": "Select sheet",
    "icon_backgroundcolor":"Change background",
    "icon_search": "Text search",
    "icon_marker": "Marker", 
    "icon_save_annotation": "Save annotation",
    "icon_marker_color": "Color",
    "icon_marker_thickness": "Thickness", 
    "icon_delete_marker": "Delete all markers",
    "icon_text_highlight": "Highlight",
    "icon_memo": "Add note",
    "icon_delete_memo": "Delete",
    "hightlight_color_yellow": "Yellow",
    "hightlight_color_green": "Green",
    "hightlight_color_blue": "Light blue",
    "hightlight_color_pink": "Pink",
    "hightlight_color_none": "Remove",
    "info_company_name":"Company/Agency",
    "info_product_name_version_key":"Product Version",
    "info_product_name_version_value":"Synap Document Viewer 2019",
    "into_product_copyright":"Copyright ⓒ Synapsoft Corp. All rights reserved.",
    "info_menu": "Information",
    "sns_title": "Share",
    "sns_url_copy": "copy URL",
    "sns_url_select": "select URL",
    "sns_url_copy_completed": "URL has been copied",
    "print_menu": "Print",
    "dialog":"Notification Dialog",
    "dialog_logo":"Company logo",
    "dialog-passwd":"Password field",
    "input-searchword": "Enter the search word",
    "input_limit_searchword": "Please enter search term within 10 characters",
    "empty-searchword": "Not found search word.",
    "none_move_search": "No previous/next search results.",
    "input_author": "author"
}